/**************************************************************************/
/* Isis glu13 interface library 
   automatically generated by the Isis header file conversion utility
   written by Stefan Agamanolis */

#include <stdlib.h>
#include <stdio.h>
#include <isis.h>

#define GLU_VERSION_1_2 1

#include "isis_glu13.h"
#include <GL/glu.h>

/**************************************************************************/

Value *isis_gluLookAt(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluOrtho2D(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluPerspective(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluPickMatrix(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluProject(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluUnProject(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluErrorString(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluScaleImage(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluBuild1DMipmaps(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluBuild2DMipmaps(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluNewQuadric(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluDeleteQuadric(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluQuadricDrawStyle(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluQuadricOrientation(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluQuadricNormals(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluQuadricTexture(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluQuadricCallback(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluCylinder(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluSphere(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluDisk(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluPartialDisk(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluNewNurbsRenderer(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluDeleteNurbsRenderer(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluLoadSamplingMatrices(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluNurbsProperty(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluGetNurbsProperty(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluBeginCurve(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluEndCurve(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluNurbsCurve(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluBeginSurface(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluEndSurface(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluNurbsSurface(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluBeginTrim(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluEndTrim(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluPwlCurve(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluNurbsCallback(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluBeginPolygon(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluNextContour(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluEndPolygon(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_gluGetString(Script *script, char *proc_name, int call_data, int argc, Value **argv);

/**************************************************************************/

static Script *localscript;

Value *isis_glu13_update_callback_slot(Script *script, char *proc_name, int call_data, int argc, Value **argv);

void glu_quadric_error(GLenum errno);
void glu_nurbs_error(GLenum errno);

static Procedure *glu_quadric_error_proc = NULL;
static Procedure *glu_nurbs_error_proc = NULL;

/**************************************************************************/

void bind_glu13_library(Script *script)
{
  bindBool(script, "isis_glu13", 1);

  localscript = script;

  bindCfunc(script, "gluLookAt", isis_gluLookAt, 0);
  bindCfunc(script, "gluOrtho2D", isis_gluOrtho2D, 0);
  bindCfunc(script, "gluPerspective", isis_gluPerspective, 0);
  bindCfunc(script, "gluPickMatrix", isis_gluPickMatrix, 0);
  bindCfunc(script, "gluProject", isis_gluProject, 0);
  bindCfunc(script, "gluUnProject", isis_gluUnProject, 0);
  bindCfunc(script, "gluErrorString", isis_gluErrorString, 0);
  bindCfunc(script, "gluScaleImage", isis_gluScaleImage, 0);
  bindCfunc(script, "gluBuild1DMipmaps", isis_gluBuild1DMipmaps, 0);
  bindCfunc(script, "gluBuild2DMipmaps", isis_gluBuild2DMipmaps, 0);
  bindCfunc(script, "gluNewQuadric", isis_gluNewQuadric, 0);
  bindCfunc(script, "gluDeleteQuadric", isis_gluDeleteQuadric, 0);
  bindCfunc(script, "gluQuadricDrawStyle", isis_gluQuadricDrawStyle, 0);
  bindCfunc(script, "gluQuadricOrientation", isis_gluQuadricOrientation, 0);
  bindCfunc(script, "gluQuadricNormals", isis_gluQuadricNormals, 0);
  bindCfunc(script, "gluQuadricTexture", isis_gluQuadricTexture, 0);
  bindCfunc(script, "gluQuadricCallback", isis_gluQuadricCallback, 0);
  bindCfunc(script, "gluCylinder", isis_gluCylinder, 0);
  bindCfunc(script, "gluSphere", isis_gluSphere, 0);
  bindCfunc(script, "gluDisk", isis_gluDisk, 0);
  bindCfunc(script, "gluPartialDisk", isis_gluPartialDisk, 0);
  bindCfunc(script, "gluNewNurbsRenderer", isis_gluNewNurbsRenderer, 0);
  bindCfunc(script, "gluDeleteNurbsRenderer", isis_gluDeleteNurbsRenderer, 0);
  bindCfunc(script, "gluLoadSamplingMatrices", isis_gluLoadSamplingMatrices, 0);
  bindCfunc(script, "gluNurbsProperty", isis_gluNurbsProperty, 0);
  bindCfunc(script, "gluGetNurbsProperty", isis_gluGetNurbsProperty, 0);
  bindCfunc(script, "gluBeginCurve", isis_gluBeginCurve, 0);
  bindCfunc(script, "gluEndCurve", isis_gluEndCurve, 0);
  bindCfunc(script, "gluNurbsCurve", isis_gluNurbsCurve, 0);
  bindCfunc(script, "gluBeginSurface", isis_gluBeginSurface, 0);
  bindCfunc(script, "gluEndSurface", isis_gluEndSurface, 0);
  bindCfunc(script, "gluNurbsSurface", isis_gluNurbsSurface, 0);
  bindCfunc(script, "gluBeginTrim", isis_gluBeginTrim, 0);
  bindCfunc(script, "gluEndTrim", isis_gluEndTrim, 0);
  bindCfunc(script, "gluPwlCurve", isis_gluPwlCurve, 0);
  bindCfunc(script, "gluNurbsCallback", isis_gluNurbsCallback, 0);
  bindCfunc(script, "gluBeginPolygon", isis_gluBeginPolygon, 0);
  bindCfunc(script, "gluNextContour", isis_gluNextContour, 0);
  bindCfunc(script, "gluEndPolygon", isis_gluEndPolygon, 0);
  bindCfunc(script, "gluGetString", isis_gluGetString, 0);

  bindCfunc(script, "update-glu13-callback-slot", isis_glu13_update_callback_slot, 0);

  bindAddr(script, "glu_quadric_error", glu_quadric_error);
  bindAddr(script, "glu_nurbs_error", glu_nurbs_error);

  bindAddr(script, "glu_quadric_error_slot", &glu_quadric_error_proc);
  bindAddr(script, "glu_nurbs_error_slot", &glu_nurbs_error_proc);

  bindInt(script, "GLU_TRUE",  GLU_TRUE);
  bindInt(script, "GLU_FALSE",  GLU_FALSE);
  bindInt(script, "GLU_SMOOTH",  GLU_SMOOTH);
  bindInt(script, "GLU_FLAT",  GLU_FLAT);
  bindInt(script, "GLU_NONE",  GLU_NONE);
  bindInt(script, "GLU_POINT",  GLU_POINT);
  bindInt(script, "GLU_LINE",  GLU_LINE);
  bindInt(script, "GLU_FILL",  GLU_FILL);
  bindInt(script, "GLU_SILHOUETTE",  GLU_SILHOUETTE);
  bindInt(script, "GLU_OUTSIDE",  GLU_OUTSIDE);
  bindInt(script, "GLU_INSIDE",  GLU_INSIDE);
  bindInt(script, "GLU_AUTO_LOAD_MATRIX",  GLU_AUTO_LOAD_MATRIX);
  bindInt(script, "GLU_CULLING",  GLU_CULLING);
  bindInt(script, "GLU_PARAMETRIC_TOLERANCE",  GLU_PARAMETRIC_TOLERANCE);
  bindInt(script, "GLU_SAMPLING_TOLERANCE",  GLU_SAMPLING_TOLERANCE);
  bindInt(script, "GLU_DISPLAY_MODE",  GLU_DISPLAY_MODE);
  bindInt(script, "GLU_SAMPLING_METHOD",  GLU_SAMPLING_METHOD);
  bindInt(script, "GLU_U_STEP",  GLU_U_STEP);
  bindInt(script, "GLU_V_STEP",  GLU_V_STEP);
  bindInt(script, "GLU_PATH_LENGTH",  GLU_PATH_LENGTH);
  bindInt(script, "GLU_PARAMETRIC_ERROR",  GLU_PARAMETRIC_ERROR);
  bindInt(script, "GLU_DOMAIN_DISTANCE",  GLU_DOMAIN_DISTANCE);
  bindInt(script, "GLU_MAP1_TRIM_2",  GLU_MAP1_TRIM_2);
  bindInt(script, "GLU_MAP1_TRIM_3",  GLU_MAP1_TRIM_3);
  bindInt(script, "GLU_OUTLINE_POLYGON",  GLU_OUTLINE_POLYGON);
  bindInt(script, "GLU_OUTLINE_PATCH",  GLU_OUTLINE_PATCH);
  bindInt(script, "GLU_NURBS_ERROR1",  GLU_NURBS_ERROR1);
  bindInt(script, "GLU_NURBS_ERROR2",  GLU_NURBS_ERROR2);
  bindInt(script, "GLU_NURBS_ERROR3",  GLU_NURBS_ERROR3);
  bindInt(script, "GLU_NURBS_ERROR4",  GLU_NURBS_ERROR4);
  bindInt(script, "GLU_NURBS_ERROR5",  GLU_NURBS_ERROR5);
  bindInt(script, "GLU_NURBS_ERROR6",  GLU_NURBS_ERROR6);
  bindInt(script, "GLU_NURBS_ERROR7",  GLU_NURBS_ERROR7);
  bindInt(script, "GLU_NURBS_ERROR8",  GLU_NURBS_ERROR8);
  bindInt(script, "GLU_NURBS_ERROR9",  GLU_NURBS_ERROR9);
  bindInt(script, "GLU_NURBS_ERROR10",  GLU_NURBS_ERROR10);
  bindInt(script, "GLU_NURBS_ERROR11",  GLU_NURBS_ERROR11);
  bindInt(script, "GLU_NURBS_ERROR12",  GLU_NURBS_ERROR12);
  bindInt(script, "GLU_NURBS_ERROR13",  GLU_NURBS_ERROR13);
  bindInt(script, "GLU_NURBS_ERROR14",  GLU_NURBS_ERROR14);
  bindInt(script, "GLU_NURBS_ERROR15",  GLU_NURBS_ERROR15);
  bindInt(script, "GLU_NURBS_ERROR16",  GLU_NURBS_ERROR16);
  bindInt(script, "GLU_NURBS_ERROR17",  GLU_NURBS_ERROR17);
  bindInt(script, "GLU_NURBS_ERROR18",  GLU_NURBS_ERROR18);
  bindInt(script, "GLU_NURBS_ERROR19",  GLU_NURBS_ERROR19);
  bindInt(script, "GLU_NURBS_ERROR20",  GLU_NURBS_ERROR20);
  bindInt(script, "GLU_NURBS_ERROR21",  GLU_NURBS_ERROR21);
  bindInt(script, "GLU_NURBS_ERROR22",  GLU_NURBS_ERROR22);
  bindInt(script, "GLU_NURBS_ERROR23",  GLU_NURBS_ERROR23);
  bindInt(script, "GLU_NURBS_ERROR24",  GLU_NURBS_ERROR24);
  bindInt(script, "GLU_NURBS_ERROR25",  GLU_NURBS_ERROR25);
  bindInt(script, "GLU_NURBS_ERROR26",  GLU_NURBS_ERROR26);
  bindInt(script, "GLU_NURBS_ERROR27",  GLU_NURBS_ERROR27);
  bindInt(script, "GLU_NURBS_ERROR28",  GLU_NURBS_ERROR28);
  bindInt(script, "GLU_NURBS_ERROR29",  GLU_NURBS_ERROR29);
  bindInt(script, "GLU_NURBS_ERROR30",  GLU_NURBS_ERROR30);
  bindInt(script, "GLU_NURBS_ERROR31",  GLU_NURBS_ERROR31);
  bindInt(script, "GLU_NURBS_ERROR32",  GLU_NURBS_ERROR32);
  bindInt(script, "GLU_NURBS_ERROR33",  GLU_NURBS_ERROR33);
  bindInt(script, "GLU_NURBS_ERROR34",  GLU_NURBS_ERROR34);
  bindInt(script, "GLU_NURBS_ERROR35",  GLU_NURBS_ERROR35);
  bindInt(script, "GLU_NURBS_ERROR36",  GLU_NURBS_ERROR36);
  bindInt(script, "GLU_NURBS_ERROR37",  GLU_NURBS_ERROR37);
  bindInt(script, "GLU_INVALID_ENUM",  GLU_INVALID_ENUM);
  bindInt(script, "GLU_INVALID_VALUE",  GLU_INVALID_VALUE);
  bindInt(script, "GLU_OUT_OF_MEMORY",  GLU_OUT_OF_MEMORY);
  bindInt(script, "GLU_VERSION",  GLU_VERSION);
  bindInt(script, "GLU_EXTENSIONS",  GLU_EXTENSIONS);
  bindInt(script, "GLU_CW",  GLU_CW);
  bindInt(script, "GLU_CCW",  GLU_CCW);
  bindInt(script, "GLU_INTERIOR",  GLU_INTERIOR);
  bindInt(script, "GLU_EXTERIOR",  GLU_EXTERIOR);
  bindInt(script, "GLU_UNKNOWN",  GLU_UNKNOWN);
  bindInt(script, "GLU_BEGIN",  GLU_BEGIN);
  bindInt(script, "GLU_VERTEX",  GLU_VERTEX);
  bindInt(script, "GLU_END",  GLU_END);
  bindInt(script, "GLU_ERROR",  GLU_ERROR);
  bindInt(script, "GLU_EDGE_FLAG",  GLU_EDGE_FLAG);

}

/**************************************************************************/

/* ---------------------------------------------------------------------- */
Value *isis_gluLookAt(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluLookAt( GLdouble eyex, GLdouble eyey, GLdouble eyez, GLdouble centerx, GLdouble centery, GLdouble centerz, GLdouble upx, GLdouble upy, GLdouble upz ); */

  checkCount(9, "eyex, eyey, eyez, centerx, centery, centerz, upx, upy, upz");

  checkReal(0, "eyex");
  checkReal(1, "eyey");
  checkReal(2, "eyez");
  checkReal(3, "centerx");
  checkReal(4, "centery");
  checkReal(5, "centerz");
  checkReal(6, "upx");
  checkReal(7, "upy");
  checkReal(8, "upz");

  gluLookAt ( (GLdouble) getReal(argv[0]),
              (GLdouble) getReal(argv[1]),
              (GLdouble) getReal(argv[2]),
              (GLdouble) getReal(argv[3]),
              (GLdouble) getReal(argv[4]),
              (GLdouble) getReal(argv[5]),
              (GLdouble) getReal(argv[6]),
              (GLdouble) getReal(argv[7]),
              (GLdouble) getReal(argv[8]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluOrtho2D(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluOrtho2D( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top ); */

  checkCount(4, "left, right, bottom, top");

  checkReal(0, "left");
  checkReal(1, "right");
  checkReal(2, "bottom");
  checkReal(3, "top");

  gluOrtho2D ( (GLdouble) getReal(argv[0]),
               (GLdouble) getReal(argv[1]),
               (GLdouble) getReal(argv[2]),
               (GLdouble) getReal(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluPerspective(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluPerspective( GLdouble fovy, GLdouble aspect, GLdouble zNear, GLdouble zFar ); */

  checkCount(4, "fovy, aspect, zNear, zFar");

  checkReal(0, "fovy");
  checkReal(1, "aspect");
  checkReal(2, "zNear");
  checkReal(3, "zFar");

  gluPerspective ( (GLdouble) getReal(argv[0]),
                   (GLdouble) getReal(argv[1]),
                   (GLdouble) getReal(argv[2]),
                   (GLdouble) getReal(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluPickMatrix(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluPickMatrix( GLdouble x, GLdouble y, GLdouble width, GLdouble height, GLint *viewport ); */

  checkCount(5, "x, y, width, height, viewport");

  checkReal(0, "x");
  checkReal(1, "y");
  checkReal(2, "width");
  checkReal(3, "height");
  checkAddr(4, "viewport");

  gluPickMatrix ( (GLdouble) getReal(argv[0]),
                  (GLdouble) getReal(argv[1]),
                  (GLdouble) getReal(argv[2]),
                  (GLdouble) getReal(argv[3]),
                  (GLint *) getAddr(argv[4]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluProject(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* GLint gluProject( GLdouble objx, GLdouble objy, GLdouble objz, GLdouble *modelMatrix, GLdouble *projMatrix, GLint *viewport, GLdouble *winx, GLdouble *winy, GLdouble *winz ); */

  checkCount(9, "objx, objy, objz, modelMatrix, projMatrix, viewport, winx, winy, winz");

  checkReal(0, "objx");
  checkReal(1, "objy");
  checkReal(2, "objz");
  checkAddr(3, "modelMatrix");
  checkAddr(4, "projMatrix");
  checkAddr(5, "viewport");
  checkAddr(6, "winx");
  checkAddr(7, "winy");
  checkAddr(8, "winz");

  return newInt( gluProject ( (GLdouble) getReal(argv[0]),
                              (GLdouble) getReal(argv[1]),
                              (GLdouble) getReal(argv[2]),
                              (GLdouble *) getAddr(argv[3]),
                              (GLdouble *) getAddr(argv[4]),
                              (GLint *) getAddr(argv[5]),
                              (GLdouble *) getAddr(argv[6]),
                              (GLdouble *) getAddr(argv[7]),
                              (GLdouble *) getAddr(argv[8]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_gluUnProject(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* GLint gluUnProject( GLdouble winx, GLdouble winy, GLdouble winz, GLdouble *modelMatrix, GLdouble *projMatrix, GLint *viewport, GLdouble *objx, GLdouble *objy, GLdouble *objz ); */

  checkCount(9, "winx, winy, winz, modelMatrix, projMatrix, viewport, objx, objy, objz");

  checkReal(0, "winx");
  checkReal(1, "winy");
  checkReal(2, "winz");
  checkAddr(3, "modelMatrix");
  checkAddr(4, "projMatrix");
  checkAddr(5, "viewport");
  checkAddr(6, "objx");
  checkAddr(7, "objy");
  checkAddr(8, "objz");

  return newInt( gluUnProject ( (GLdouble) getReal(argv[0]),
                                (GLdouble) getReal(argv[1]),
                                (GLdouble) getReal(argv[2]),
                                (GLdouble *) getAddr(argv[3]),
                                (GLdouble *) getAddr(argv[4]),
                                (GLint *) getAddr(argv[5]),
                                (GLdouble *) getAddr(argv[6]),
                                (GLdouble *) getAddr(argv[7]),
                                (GLdouble *) getAddr(argv[8]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_gluErrorString(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /*  GLubyte* gluErrorString( GLenum errorCode ); */

  char *retstr;
  Value *retval;

  checkCount(1, "errorCode");

  checkInt(0, "errorCode");

  retstr = (char *) gluErrorString ( (GLenum) getInt(argv[0]) );

  if(retstr) retval = newString(strlen(retstr), retstr);
  else retval = NullValue;

  return retval;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluScaleImage(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* GLint gluScaleImage( GLenum format, GLint widthin, GLint heightin, GLenum typein, void *datain, GLint widthout, GLint heightout, GLenum typeout, void *dataout ); */

  checkCount(9, "format, widthin, heightin, typein, datain, widthout, heightout, typeout, dataout");

  checkInt(0, "format");
  checkInt(1, "widthin");
  checkInt(2, "heightin");
  checkInt(3, "typein");
  checkAddr(4, "datain");
  checkInt(5, "widthout");
  checkInt(6, "heightout");
  checkInt(7, "typeout");
  checkAddr(8, "dataout");

  return newInt( gluScaleImage ( (GLenum) getInt(argv[0]),
                                 (GLint) getInt(argv[1]),
                                 (GLint) getInt(argv[2]),
                                 (GLenum) getInt(argv[3]),
                                 (void *) getAddr(argv[4]),
                                 (GLint) getInt(argv[5]),
                                 (GLint) getInt(argv[6]),
                                 (GLenum) getInt(argv[7]),
                                 (void *) getAddr(argv[8]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_gluBuild1DMipmaps(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* GLint gluBuild1DMipmaps( GLenum target, GLint components, GLint width, GLenum format, GLenum type, void *data ); */

  checkCount(6, "target, components, width, format, type, data");

  checkInt(0, "target");
  checkInt(1, "components");
  checkInt(2, "width");
  checkInt(3, "format");
  checkInt(4, "type");
  checkAddr(5, "data");

  return newInt( gluBuild1DMipmaps ( (GLenum) getInt(argv[0]),
                                     (GLint) getInt(argv[1]),
                                     (GLint) getInt(argv[2]),
                                     (GLenum) getInt(argv[3]),
                                     (GLenum) getInt(argv[4]),
                                     (void *) getAddr(argv[5]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_gluBuild2DMipmaps(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* GLint gluBuild2DMipmaps( GLenum target, GLint components, GLint width, GLint height, GLenum format, GLenum type, void *data ); */

  checkCount(7, "target, components, width, height, format, type, data");

  checkInt(0, "target");
  checkInt(1, "components");
  checkInt(2, "width");
  checkInt(3, "height");
  checkInt(4, "format");
  checkInt(5, "type");
  checkAddr(6, "data");

  return newInt( gluBuild2DMipmaps ( (GLenum) getInt(argv[0]),
                                     (GLint) getInt(argv[1]),
                                     (GLint) getInt(argv[2]),
                                     (GLint) getInt(argv[3]),
                                     (GLenum) getInt(argv[4]),
                                     (GLenum) getInt(argv[5]),
                                     (void *) getAddr(argv[6]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_gluNewQuadric(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* GLUquadricObj* gluNewQuadric( void ); */

  checkCount(0, NULL);


  return newAddr( (void *) gluNewQuadric (  ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_gluDeleteQuadric(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluDeleteQuadric( GLUquadricObj *state ); */

  checkCount(1, "state");

  checkAddr(0, "state");

  gluDeleteQuadric ( (GLUquadricObj *) getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluQuadricDrawStyle(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluQuadricDrawStyle( GLUquadricObj *quadObject, GLenum drawStyle ); */

  checkCount(2, "quadObject, drawStyle");

  checkAddr(0, "quadObject");
  checkInt(1, "drawStyle");

  gluQuadricDrawStyle ( (GLUquadricObj *) getAddr(argv[0]),
                        (GLenum) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluQuadricOrientation(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluQuadricOrientation( GLUquadricObj *quadObject, GLenum orientation ); */

  checkCount(2, "quadObject, orientation");

  checkAddr(0, "quadObject");
  checkInt(1, "orientation");

  gluQuadricOrientation ( (GLUquadricObj *) getAddr(argv[0]),
                          (GLenum) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluQuadricNormals(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluQuadricNormals( GLUquadricObj *quadObject, GLenum normals ); */

  checkCount(2, "quadObject, normals");

  checkAddr(0, "quadObject");
  checkInt(1, "normals");

  gluQuadricNormals ( (GLUquadricObj *) getAddr(argv[0]),
                      (GLenum) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluQuadricTexture(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluQuadricTexture( GLUquadricObj *quadObject, GLboolean textureCoords ); */

  checkCount(2, "quadObject, textureCoords");

  checkAddr(0, "quadObject");

  gluQuadricTexture ( (GLUquadricObj *) getAddr(argv[0]),
                      (GLboolean) trueValue(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluQuadricCallback(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluQuadricCallback( GLUquadricObj *qobj, GLenum which, void (*CallBackFunc)() ); */

  checkCount(3, "qobj, which, CallBackFunc");

  checkAddr(0, "qobj");
  checkInt(1, "which");
  checkAddr(2, "CallBackFunc");

  gluQuadricCallback ( (GLUquadricObj *) getAddr(argv[0]),
                       (GLenum) getInt(argv[1]),
                       getAddr(argv[2]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluCylinder(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluCylinder( GLUquadricObj *qobj, GLdouble baseRadius, GLdouble topRadius, GLdouble height, GLint slices, GLint stacks ); */

  checkCount(6, "qobj, baseRadius, topRadius, height, slices, stacks");

  checkAddr(0, "qobj");
  checkReal(1, "baseRadius");
  checkReal(2, "topRadius");
  checkReal(3, "height");
  checkInt(4, "slices");
  checkInt(5, "stacks");

  gluCylinder ( (GLUquadricObj *) getAddr(argv[0]),
                (GLdouble) getReal(argv[1]),
                (GLdouble) getReal(argv[2]),
                (GLdouble) getReal(argv[3]),
                (GLint) getInt(argv[4]),
                (GLint) getInt(argv[5]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluSphere(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluSphere( GLUquadricObj *qobj, GLdouble radius, GLint slices, GLint stacks ); */

  checkCount(4, "qobj, radius, slices, stacks");

  checkAddr(0, "qobj");
  checkReal(1, "radius");
  checkInt(2, "slices");
  checkInt(3, "stacks");

  gluSphere ( (GLUquadricObj *) getAddr(argv[0]),
              (GLdouble) getReal(argv[1]),
              (GLint) getInt(argv[2]),
              (GLint) getInt(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluDisk(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluDisk( GLUquadricObj *qobj, GLdouble innerRadius, GLdouble outerRadius, GLint slices, GLint loops ); */

  checkCount(5, "qobj, innerRadius, outerRadius, slices, loops");

  checkAddr(0, "qobj");
  checkReal(1, "innerRadius");
  checkReal(2, "outerRadius");
  checkInt(3, "slices");
  checkInt(4, "loops");

  gluDisk ( (GLUquadricObj *) getAddr(argv[0]),
            (GLdouble) getReal(argv[1]),
            (GLdouble) getReal(argv[2]),
            (GLint) getInt(argv[3]),
            (GLint) getInt(argv[4]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluPartialDisk(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluPartialDisk( GLUquadricObj *qobj, GLdouble innerRadius, GLdouble outerRadius, GLint slices, GLint loops, GLdouble startAngle, GLdouble sweepAngle ); */

  checkCount(7, "qobj, innerRadius, outerRadius, slices, loops, startAngle, sweepAngle");

  checkAddr(0, "qobj");
  checkReal(1, "innerRadius");
  checkReal(2, "outerRadius");
  checkInt(3, "slices");
  checkInt(4, "loops");
  checkReal(5, "startAngle");
  checkReal(6, "sweepAngle");

  gluPartialDisk ( (GLUquadricObj *) getAddr(argv[0]),
                   (GLdouble) getReal(argv[1]),
                   (GLdouble) getReal(argv[2]),
                   (GLint) getInt(argv[3]),
                   (GLint) getInt(argv[4]),
                   (GLdouble) getReal(argv[5]),
                   (GLdouble) getReal(argv[6]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluNewNurbsRenderer(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* GLUnurbsObj* gluNewNurbsRenderer( void ); */

  checkCount(0, NULL);


  return newAddr( (void *) gluNewNurbsRenderer (  ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_gluDeleteNurbsRenderer(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluDeleteNurbsRenderer( GLUnurbsObj *nobj ); */

  checkCount(1, "nobj");

  checkAddr(0, "nobj");

  gluDeleteNurbsRenderer ( (GLUnurbsObj *) getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluLoadSamplingMatrices(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluLoadSamplingMatrices( GLUnurbsObj *nobj, GLfloat *modelMatrix, GLfloat *projMatrix, GLint *viewport ); */

  checkCount(4, "nobj, modelMatrix, projMatrix, viewport");

  checkAddr(0, "nobj");
  checkAddr(1, "modelMatrix");
  checkAddr(2, "projMatrix");
  checkAddr(3, "viewport");

  gluLoadSamplingMatrices ( (GLUnurbsObj *) getAddr(argv[0]),
                            (GLfloat *) getAddr(argv[1]),
                            (GLfloat *) getAddr(argv[2]),
                            (GLint *) getAddr(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluNurbsProperty(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluNurbsProperty( GLUnurbsObj *nobj, GLenum property, GLfloat value ); */

  checkCount(3, "nobj, property, value");

  checkAddr(0, "nobj");
  checkInt(1, "property");
  checkReal(2, "value");

  gluNurbsProperty ( (GLUnurbsObj *) getAddr(argv[0]),
                     (GLenum) getInt(argv[1]),
                     (GLfloat) getReal(argv[2]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluGetNurbsProperty(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluGetNurbsProperty( GLUnurbsObj *nobj, GLenum property, GLfloat *value ); */

  checkCount(3, "nobj, property, value");

  checkAddr(0, "nobj");
  checkInt(1, "property");
  checkAddr(2, "value");

  gluGetNurbsProperty ( (GLUnurbsObj *) getAddr(argv[0]),
                        (GLenum) getInt(argv[1]),
                        (GLfloat *) getAddr(argv[2]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluBeginCurve(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluBeginCurve( GLUnurbsObj *nobj ); */

  checkCount(1, "nobj");

  checkAddr(0, "nobj");

  gluBeginCurve ( (GLUnurbsObj *) getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluEndCurve(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluEndCurve( GLUnurbsObj * nobj ); */

  checkCount(1, "nobj");

  checkAddr(0, "nobj");

  gluEndCurve ( (GLUnurbsObj *) getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluNurbsCurve(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluNurbsCurve( GLUnurbsObj *nobj, GLint nknots, GLfloat *knot, GLint stride, GLfloat *ctlarray, GLint order, GLenum type ); */

  checkCount(7, "nobj, nknots, knot, stride, ctlarray, order, type");

  checkAddr(0, "nobj");
  checkInt(1, "nknots");
  checkAddr(2, "knot");
  checkInt(3, "stride");
  checkAddr(4, "ctlarray");
  checkInt(5, "order");
  checkInt(6, "type");

  gluNurbsCurve ( (GLUnurbsObj *) getAddr(argv[0]),
                  (GLint) getInt(argv[1]),
                  (GLfloat *) getAddr(argv[2]),
                  (GLint) getInt(argv[3]),
                  (GLfloat *) getAddr(argv[4]),
                  (GLint) getInt(argv[5]),
                  (GLenum) getInt(argv[6]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluBeginSurface(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluBeginSurface( GLUnurbsObj *nobj ); */

  checkCount(1, "nobj");

  checkAddr(0, "nobj");

  gluBeginSurface ( (GLUnurbsObj *) getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluEndSurface(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluEndSurface( GLUnurbsObj * nobj ); */

  checkCount(1, "nobj");

  checkAddr(0, "nobj");

  gluEndSurface ( (GLUnurbsObj *) getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluNurbsSurface(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluNurbsSurface( GLUnurbsObj *nobj, GLint sknot_count, GLfloat *sknot, GLint tknot_count, GLfloat *tknot, GLint s_stride, GLint t_stride, GLfloat *ctlarray, GLint sorder, GLint torder, GLenum type ); */

  checkCount(11, "nobj, sknot_count, sknot, tknot_count, tknot, s_stride, t_stride, ctlarray, sorder, torder, type");

  checkAddr(0, "nobj");
  checkInt(1, "sknot_count");
  checkAddr(2, "sknot");
  checkInt(3, "tknot_count");
  checkAddr(4, "tknot");
  checkInt(5, "s_stride");
  checkInt(6, "t_stride");
  checkAddr(7, "ctlarray");
  checkInt(8, "sorder");
  checkInt(9, "torder");
  checkInt(10, "type");

  gluNurbsSurface ( (GLUnurbsObj *) getAddr(argv[0]),
                    (GLint) getInt(argv[1]),
                    (GLfloat *) getAddr(argv[2]),
                    (GLint) getInt(argv[3]),
                    (GLfloat *) getAddr(argv[4]),
                    (GLint) getInt(argv[5]),
                    (GLint) getInt(argv[6]),
                    (GLfloat *) getAddr(argv[7]),
                    (GLint) getInt(argv[8]),
                    (GLint) getInt(argv[9]),
                    (GLenum) getInt(argv[10]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluBeginTrim(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluBeginTrim( GLUnurbsObj *nobj ); */

  checkCount(1, "nobj");

  checkAddr(0, "nobj");

  gluBeginTrim ( (GLUnurbsObj *) getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluEndTrim(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluEndTrim( GLUnurbsObj *nobj ); */

  checkCount(1, "nobj");

  checkAddr(0, "nobj");

  gluEndTrim ( (GLUnurbsObj *) getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluPwlCurve(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluPwlCurve( GLUnurbsObj *nobj, GLint count, GLfloat *array, GLint stride, GLenum type ); */

  checkCount(5, "nobj, count, array, stride, type");

  checkAddr(0, "nobj");
  checkInt(1, "count");
  checkAddr(2, "array");
  checkInt(3, "stride");
  checkInt(4, "type");

  gluPwlCurve ( (GLUnurbsObj *) getAddr(argv[0]),
                (GLint) getInt(argv[1]),
                (GLfloat *) getAddr(argv[2]),
                (GLint) getInt(argv[3]),
                (GLenum) getInt(argv[4]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluNurbsCallback(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluNurbsCallback( GLUnurbsObj *nobj, GLenum which, void (*CallBackFunc)() ); */

  checkCount(3, "nobj, which, CallBackFunc");

  checkAddr(0, "nobj");
  checkInt(1, "which");
  checkAddr(2, "CallBackFunc");

  gluNurbsCallback ( (GLUnurbsObj *) getAddr(argv[0]),
                     (GLenum) getInt(argv[1]),
                     getAddr(argv[2]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluBeginPolygon(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluBeginPolygon( GLUtesselator *tobj ); */

  checkCount(1, "tobj");

  checkAddr(0, "tobj");

  gluBeginPolygon ( (GLUtesselator *) getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluNextContour(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluNextContour( GLUtesselator *tobj, GLenum type ); */

  checkCount(2, "tobj, type");

  checkAddr(0, "tobj");
  checkInt(1, "type");

  gluNextContour ( (GLUtesselator *) getAddr(argv[0]),
                   (GLenum) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluEndPolygon(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void gluEndPolygon( GLUtesselator *tobj ); */

  checkCount(1, "tobj");

  checkAddr(0, "tobj");

  gluEndPolygon ( (GLUtesselator *) getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_gluGetString(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* GLubyte* gluGetString( GLenum name ); */

  char *retstr;
  Value *retval;

  checkCount(1, "name");

  checkInt(0, "name");

  retstr = (char *) gluGetString ( (GLenum) getInt(argv[0]) );

  if(retstr) retval = newString(strlen(retstr), retstr);
  else retval = NullValue;

  return retval;
}


/**************************************************************************/

/* ---------------------------------------------------------------------- */
Value *isis_glu13_update_callback_slot(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  Procedure **procaddr;
  
  checkCount(2, "callback slot, callback procedure");
  checkAddr(0, "callback slot");
  if(!isNull(argv[1])) checkProc(1, "callback procedure");
  
  procaddr = (Procedure **) getAddr(argv[0]);
  if(*procaddr != NULL) freeProcedure(*procaddr);
  if(isNull(argv[1])) *procaddr = NULL;
  else *procaddr = referProcedure(getProc(argv[1]));
  
  return NullValue;
}

/* ---------------------------------------------------------------------- */
void glu_quadric_error(GLenum errno)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(1);

  argv[0] = newInt(errno);

  val = applyProcedure(localscript, glu_quadric_error_proc, 1, argv);

  for(i = 0; i < 1; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glu_nurbs_error(GLenum errno)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(1);

  argv[0] = newInt(errno);

  val = applyProcedure(localscript, glu_nurbs_error_proc, 1, argv);

  for(i = 0; i < 1; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

