/**************************************************************************/
/* Isis glx interface library 
   automatically generated by the Isis header file conversion utility
   written by Stefan Agamanolis, February 1998 */

#include <stdlib.h>
#include <stdio.h>
#include <isis.h>

#include "isis_glx.h"

#include <GL/glx.h>

/**************************************************************************/

Value *isis_glXChooseVisual(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glXCopyContext(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glXCreateContext(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv);
Value *isis_glXCreateGLXPixmap(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv);
Value *isis_glXDestroyContext(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv);
Value *isis_glXDestroyGLXPixmap(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv);
Value *isis_glXGetConfig(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv);
Value *isis_glXGetCurrentContext(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv);
Value *isis_glXGetCurrentDrawable(Script *script, char *proc_name, int call_data, 
                                  int argc, Value **argv);
Value *isis_glXIsDirect(Script *script, char *proc_name, int call_data, 
                        int argc, Value **argv);
Value *isis_glXMakeCurrent(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glXQueryExtension(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv);
Value *isis_glXQueryVersion(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glXSwapBuffers(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glXUseXFont(Script *script, char *proc_name, int call_data, 
                        int argc, Value **argv);
Value *isis_glXWaitGL(Script *script, char *proc_name, int call_data, 
                      int argc, Value **argv);
Value *isis_glXWaitX(Script *script, char *proc_name, int call_data, 
                     int argc, Value **argv);
Value *isis_glXGetClientString(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv);
Value *isis_glXQueryServerString(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv);
Value *isis_glXQueryExtensionsString(Script *script, char *proc_name, int call_data, 
                                     int argc, Value **argv);

/**************************************************************************/

void bind_glx_library(Script *script)
{
  bindBool(script, "isis_glx", 1);

  bindCfunc(script, "glXChooseVisual", isis_glXChooseVisual, 0);
  bindCfunc(script, "glXCopyContext", isis_glXCopyContext, 0);
  bindCfunc(script, "glXCreateContext", isis_glXCreateContext, 0);
  bindCfunc(script, "glXCreateGLXPixmap", isis_glXCreateGLXPixmap, 0);
  bindCfunc(script, "glXDestroyContext", isis_glXDestroyContext, 0);
  bindCfunc(script, "glXDestroyGLXPixmap", isis_glXDestroyGLXPixmap, 0);
  bindCfunc(script, "glXGetConfig", isis_glXGetConfig, 0);
  bindCfunc(script, "glXGetCurrentContext", isis_glXGetCurrentContext, 0);
  bindCfunc(script, "glXGetCurrentDrawable", isis_glXGetCurrentDrawable, 0);
  bindCfunc(script, "glXIsDirect", isis_glXIsDirect, 0);
  bindCfunc(script, "glXMakeCurrent", isis_glXMakeCurrent, 0);
  bindCfunc(script, "glXQueryExtension", isis_glXQueryExtension, 0);
  bindCfunc(script, "glXQueryVersion", isis_glXQueryVersion, 0);
  bindCfunc(script, "glXSwapBuffers", isis_glXSwapBuffers, 0);
  bindCfunc(script, "glXUseXFont", isis_glXUseXFont, 0);
  bindCfunc(script, "glXWaitGL", isis_glXWaitGL, 0);
  bindCfunc(script, "glXWaitX", isis_glXWaitX, 0);
  bindCfunc(script, "glXGetClientString", isis_glXGetClientString, 0);
  bindCfunc(script, "glXQueryServerString", isis_glXQueryServerString, 0);
  bindCfunc(script, "glXQueryExtensionsString", isis_glXQueryExtensionsString, 0);

}

/**************************************************************************/

/* ---------------------------------------------------------------------- */
Value *isis_glXChooseVisual(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern XVisualInfo* glXChooseVisual (Display *dpy, int screen, int *attribList); */

  checkCount(3, "dpy, screen, attribList");

  checkAddr(0, "dpy");
  checkInt(1, "screen");
  checkAddr(2, "attribList");

  return newAddr( glXChooseVisual ( (Display *) getAddr(argv[0]),
                                    (int) getInt(argv[1]),
                                    (int *) getAddr(argv[2]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glXCopyContext(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glXCopyContext (Display *dpy, GLXContext src, GLXContext dst, unsigned long mask); */

  checkCount(4, "dpy, src, dst, mask");

  checkAddr(0, "dpy");
  checkAddr(1, "src");
  checkAddr(2, "dst");
  checkInt(3, "mask");

  glXCopyContext ( (Display *) getAddr(argv[0]),
                   (GLXContext) getAddr(argv[1]),
                   (GLXContext) getAddr(argv[2]),
                   (unsigned long) getInt(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glXCreateContext(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv)
{
  /* extern GLXContext glXCreateContext (Display *dpy, XVisualInfo *vis, GLXContext shareList, Bool direct); */

  checkCount(4, "dpy, vis, shareList, direct");

  checkAddr(0, "dpy");
  checkAddr(1, "vis");
  checkAddr(2, "shareList");

  return newAddr( glXCreateContext ( (Display *) getAddr(argv[0]),
                                     (XVisualInfo *) getAddr(argv[1]),
                                     (GLXContext) getAddr(argv[2]),
                                     (Bool) trueValue(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glXCreateGLXPixmap(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv)
{
  /* extern GLXPixmap glXCreateGLXPixmap (Display *dpy, XVisualInfo *vis, Pixmap pixmap); */

  checkCount(3, "dpy, vis, pixmap");

  checkAddr(0, "dpy");
  checkAddr(1, "vis");
  checkInt(2, "pixmap");

  return newInt( glXCreateGLXPixmap ( (Display *) getAddr(argv[0]),
                                      (XVisualInfo *) getAddr(argv[1]),
                                      (Pixmap) getInt(argv[2]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glXDestroyContext(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv)
{
  /* extern void glXDestroyContext (Display *dpy, GLXContext ctx); */

  checkCount(2, "dpy, ctx");

  checkAddr(0, "dpy");
  checkAddr(1, "ctx");

  glXDestroyContext ( (Display *) getAddr(argv[0]),
                      (GLXContext) getAddr(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glXDestroyGLXPixmap(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv)
{
  /* extern void glXDestroyGLXPixmap (Display *dpy, GLXPixmap pix); */

  checkCount(2, "dpy, pix");

  checkAddr(0, "dpy");
  checkInt(1, "pix");

  glXDestroyGLXPixmap ( (Display *) getAddr(argv[0]),
                        (GLXPixmap) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glXGetConfig(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv)
{
  /* extern int glXGetConfig (Display *dpy, XVisualInfo *vis, int attrib, int *value); */

  checkCount(4, "dpy, vis, attrib, value");

  checkAddr(0, "dpy");
  checkAddr(1, "vis");
  checkInt(2, "attrib");
  checkAddr(3, "value");

  return newInt( glXGetConfig ( (Display *) getAddr(argv[0]),
                                (XVisualInfo *) getAddr(argv[1]),
                                (int) getInt(argv[2]),
                                (int *) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glXGetCurrentContext(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv)
{
  /* extern GLXContext glXGetCurrentContext (void); */

  checkCount(0, NULL);


  return newAddr( glXGetCurrentContext (  ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glXGetCurrentDrawable(Script *script, char *proc_name, int call_data, 
                                  int argc, Value **argv)
{
  /* extern GLXDrawable glXGetCurrentDrawable (void); */

  checkCount(0, NULL);


  return newInt( glXGetCurrentDrawable (  ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glXIsDirect(Script *script, char *proc_name, int call_data, 
                        int argc, Value **argv)
{
  /* extern Bool glXIsDirect (Display *dpy, GLXContext ctx); */

  checkCount(2, "dpy, ctx");

  checkAddr(0, "dpy");
  checkAddr(1, "ctx");

  return newBool( glXIsDirect ( (Display *) getAddr(argv[0]),
                                (GLXContext) getAddr(argv[1]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glXMakeCurrent(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern Bool glXMakeCurrent (Display *dpy, GLXDrawable drawable, GLXContext ctx); */

  checkCount(3, "dpy, drawable, ctx");

  checkAddr(0, "dpy");
  checkInt(1, "drawable");
  checkAddr(2, "ctx");

  return newBool( glXMakeCurrent ( (Display *) getAddr(argv[0]),
                                   (GLXDrawable) getInt(argv[1]),
                                   (GLXContext) getAddr(argv[2]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glXQueryExtension(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv)
{
  /* extern Bool glXQueryExtension (Display *dpy, int *errorBase, int *eventBase); */

  checkCount(3, "dpy, errorBase, eventBase");

  checkAddr(0, "dpy");
  checkAddr(1, "errorBase");
  checkAddr(2, "eventBase");

  return newBool( glXQueryExtension ( (Display *) getAddr(argv[0]),
                                      (int *) getAddr(argv[1]),
                                      (int *) getAddr(argv[2]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glXQueryVersion(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern Bool glXQueryVersion (Display *dpy, int *major, int *minor); */

  checkCount(3, "dpy, major, minor");

  checkAddr(0, "dpy");
  checkAddr(1, "major");
  checkAddr(2, "minor");

  return newBool( glXQueryVersion ( (Display *) getAddr(argv[0]),
                                    (int *) getAddr(argv[1]),
                                    (int *) getAddr(argv[2]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glXSwapBuffers(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glXSwapBuffers (Display *dpy, GLXDrawable drawable); */

  checkCount(2, "dpy, drawable");

  checkAddr(0, "dpy");
  checkInt(1, "drawable");

  glXSwapBuffers ( (Display *) getAddr(argv[0]),
                   (GLXDrawable) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glXUseXFont(Script *script, char *proc_name, int call_data, 
                        int argc, Value **argv)
{
  /* extern void glXUseXFont (Font font, int first, int count, int listBase); */

  checkCount(4, "font, first, count, listBase");

  checkInt(0, "font");
  checkInt(1, "first");
  checkInt(2, "count");
  checkInt(3, "listBase");

  glXUseXFont ( (Font) getInt(argv[0]),
                (int) getInt(argv[1]),
                (int) getInt(argv[2]),
                (int) getInt(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glXWaitGL(Script *script, char *proc_name, int call_data, 
                      int argc, Value **argv)
{
  /* extern void glXWaitGL (void); */

  checkCount(0, NULL);


  glXWaitGL (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glXWaitX(Script *script, char *proc_name, int call_data, 
                     int argc, Value **argv)
{
  /* extern void glXWaitX (void); */

  checkCount(0, NULL);


  glXWaitX (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glXGetClientString(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv)
{
  /* extern const char * glXGetClientString (Display *dpy, int name ); */

  char *retstr;
  Value *retval;

  checkCount(2, "dpy, name");

  checkAddr(0, "dpy");
  checkInt(1, "name");

  retstr = (char *) glXGetClientString ( (Display *) getAddr(argv[0]),
                                         (int) getInt(argv[1]) );

  if(retstr) retval = newString(strlen(retstr), retstr);
  else retval = NullValue;

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glXQueryServerString(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv)
{
  /* extern const char * glXQueryServerString (Display *dpy, int screen, int name ); */

  char *retstr;
  Value *retval;

  checkCount(3, "dpy, screen, name");

  checkAddr(0, "dpy");
  checkInt(1, "screen");
  checkInt(2, "name");

  retstr = (char *) glXQueryServerString ( (Display *) getAddr(argv[0]),
                                           (int) getInt(argv[1]),
                                           (int) getInt(argv[2]) );

  if(retstr) retval = newString(strlen(retstr), retstr);
  else retval = NullValue;

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glXQueryExtensionsString(Script *script, char *proc_name, int call_data, 
                                     int argc, Value **argv)
{
  /* extern const char * glXQueryExtensionsString (Display *dpy, int screen ); */

  char *retstr;
  Value *retval;

  checkCount(2, "dpy, screen");

  checkAddr(0, "dpy");
  checkInt(1, "screen");

  retstr = (char *) glXQueryExtensionsString ( (Display *) getAddr(argv[0]),
                                               (int) getInt(argv[1]) );

  if(retstr) retval = newString(strlen(retstr), retstr);
  else retval = NullValue;

  return NullValue;
}

