/**************************************************************************/
/* Isis cmuface interface library 
   automatically generated by the Isis header file conversion utility
   written by Stefan Agamanolis */

#include <stdlib.h>
#include <stdio.h>
#include <isis.h>

#include "isis_cmuface.h"

#include <detect.h>

/**************************************************************************/

Value *isis_SearchEye(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Informedia_FindFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Informedia_FindFacesRGBA(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Informedia_FindFacesOrientation(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Informedia_FindFacesAllCandidates(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Informedia_FindFacesGray(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Informedia_FindFacesOrientationGray(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Xavier_FindAllFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Xavier_FindAllFacesColor(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Xavier_FindOneFace(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Xavier_FindOneFaceColor(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Slow_FindAllFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Track_FindAllFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Track_FindAllFacesRegion(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Siemens_FindAllFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Astro_FindAllFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Rotation_FindAllFacesSlow(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_Rotation_FindAllFacesSlowExtract(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_BroadenColorMask(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_UpdateColorMaskFromBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_LoadGifToBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_LoadPgmToBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_LoadPpmToBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_LoadPgmStreamToBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_LoadPpmStreamToBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_SetDataPath(Script *script, char *proc_name, int call_data, int argc, Value **argv);

/**************************************************************************/

static Script *localscript;

Value *isis_cmuface_update_callback_slot(Script *script, char *proc_name, int call_data, int argc, Value **argv);

int *isis_Informedia_CandidateCallback(double candidateRating, int xc, int yc, int sc, double verifyRating1, int x1, int y1, int s1, double verifyRating2, int x2, int y2, int s2);

static Procedure *isis_Informedia_CandidateCallback_proc = NULL;

/**************************************************************************/

void bind_cmuface_library(Script *script)
{
  bindBool(script, "isis_cmuface", 1);

  localscript = script;

  bindCfunc(script, "SearchEye", isis_SearchEye, 0);
  bindCfunc(script, "Informedia_FindFaces", isis_Informedia_FindFaces, 0);
  bindCfunc(script, "Informedia_FindFacesRGBA", isis_Informedia_FindFacesRGBA, 0);
  bindCfunc(script, "Informedia_FindFacesOrientation", isis_Informedia_FindFacesOrientation, 0);
  bindCfunc(script, "Informedia_FindFacesAllCandidates", isis_Informedia_FindFacesAllCandidates, 0);
  bindCfunc(script, "Informedia_FindFacesGray", isis_Informedia_FindFacesGray, 0);
  bindCfunc(script, "Informedia_FindFacesOrientationGray", isis_Informedia_FindFacesOrientationGray, 0);
  bindCfunc(script, "Xavier_FindAllFaces", isis_Xavier_FindAllFaces, 0);
  bindCfunc(script, "Xavier_FindAllFacesColor", isis_Xavier_FindAllFacesColor, 0);
  bindCfunc(script, "Xavier_FindOneFace", isis_Xavier_FindOneFace, 0);
  bindCfunc(script, "Xavier_FindOneFaceColor", isis_Xavier_FindOneFaceColor, 0);
  bindCfunc(script, "Slow_FindAllFaces", isis_Slow_FindAllFaces, 0);
  bindCfunc(script, "Track_FindAllFaces", isis_Track_FindAllFaces, 0);
  bindCfunc(script, "Track_FindAllFacesRegion", isis_Track_FindAllFacesRegion, 0);
  bindCfunc(script, "Siemens_FindAllFaces", isis_Siemens_FindAllFaces, 0);
  bindCfunc(script, "Astro_FindAllFaces", isis_Astro_FindAllFaces, 0);
  bindCfunc(script, "Rotation_FindAllFacesSlow", isis_Rotation_FindAllFacesSlow, 0);
  bindCfunc(script, "Rotation_FindAllFacesSlowExtract", isis_Rotation_FindAllFacesSlowExtract, 0);
  bindCfunc(script, "BroadenColorMask", isis_BroadenColorMask, 0);
  bindCfunc(script, "UpdateColorMaskFromBuffer", isis_UpdateColorMaskFromBuffer, 0);
  bindCfunc(script, "LoadGifToBuffer", isis_LoadGifToBuffer, 0);
  bindCfunc(script, "LoadPgmToBuffer", isis_LoadPgmToBuffer, 0);
  bindCfunc(script, "LoadPpmToBuffer", isis_LoadPpmToBuffer, 0);
  bindCfunc(script, "LoadPgmStreamToBuffer", isis_LoadPgmStreamToBuffer, 0);
  bindCfunc(script, "LoadPpmStreamToBuffer", isis_LoadPpmStreamToBuffer, 0);
  bindCfunc(script, "SetDataPath", isis_SetDataPath, 0);

  bindCfunc(script, "update-cmuface-callback-slot", isis_cmuface_update_callback_slot, 0);

  bindAddr(script, "isis_Informedia_CandidateCallback", isis_Informedia_CandidateCallback);

  bindAddr(script, "isis_Informedia_CandidateCallback_slot", &isis_Informedia_CandidateCallback_proc);

  bindInt(script, "Xavier_NoOptimizations",  Xavier_NoOptimizations);
  bindInt(script, "Xavier_QuickVerify",  Xavier_QuickVerify);
  bindInt(script, "Xavier_CropImage",  Xavier_CropImage);
  bindInt(script, "Xavier_QuickVerifyNN",  Xavier_QuickVerifyNN);

  {
    struct FaceLocation s;

    bindInt(script, "FaceLocation-struct", sizeof(s));
    bindIntListva(script, "FaceLocation-x1", 3, 5, 0, (int) ((unsigned long) &s.x1 - (unsigned long) &s));    bindIntListva(script, "FaceLocation-y1", 3, 5, 0, (int) ((unsigned long) &s.y1 - (unsigned long) &s));    bindIntListva(script, "FaceLocation-x2", 3, 5, 0, (int) ((unsigned long) &s.x2 - (unsigned long) &s));    bindIntListva(script, "FaceLocation-y2", 3, 5, 0, (int) ((unsigned long) &s.y2 - (unsigned long) &s));  }

  {
    struct FaceLocationOrientation s;

    bindInt(script, "FaceLocationOrientation-struct", sizeof(s));
    bindIntListva(script, "FaceLocationOrientation-x1", 3, 5, 0, (int) ((unsigned long) &s.x1 - (unsigned long) &s));    bindIntListva(script, "FaceLocationOrientation-y1", 3, 5, 0, (int) ((unsigned long) &s.y1 - (unsigned long) &s));    bindIntListva(script, "FaceLocationOrientation-x2", 3, 5, 0, (int) ((unsigned long) &s.x2 - (unsigned long) &s));    bindIntListva(script, "FaceLocationOrientation-y2", 3, 5, 0, (int) ((unsigned long) &s.y2 - (unsigned long) &s));    bindIntListva(script, "FaceLocationOrientation-orientation", 3, 5, 0, (int) ((unsigned long) &s.orientation - (unsigned long) &s));  }

  {
    struct FaceLocationRotation s;

    bindInt(script, "FaceLocationRotation-struct", sizeof(s));
    bindIntListva(script, "FaceLocationRotation-x", 3, 5, 0, (int) ((unsigned long) &s.x - (unsigned long) &s));    bindIntListva(script, "FaceLocationRotation-y", 3, 5, 0, (int) ((unsigned long) &s.y - (unsigned long) &s));    bindIntListva(script, "FaceLocationRotation-angle", 3, 10, 0, (int) ((unsigned long) &s.angle - (unsigned long) &s));    bindIntListva(script, "FaceLocationRotation-size", 3, 5, 0, (int) ((unsigned long) &s.size - (unsigned long) &s));  }

  {
    struct FaceLocationRotationExtract s;

    bindInt(script, "FaceLocationRotationExtract-struct", sizeof(s));
    bindIntListva(script, "FaceLocationRotationExtract-x", 3, 5, 0, (int) ((unsigned long) &s.x - (unsigned long) &s));    bindIntListva(script, "FaceLocationRotationExtract-y", 3, 5, 0, (int) ((unsigned long) &s.y - (unsigned long) &s));    bindIntListva(script, "FaceLocationRotationExtract-angle", 3, 10, 0, (int) ((unsigned long) &s.angle - (unsigned long) &s));    bindIntListva(script, "FaceLocationRotationExtract-size", 3, 5, 0, (int) ((unsigned long) &s.size - (unsigned long) &s));    bindIntListva(script, "FaceLocationRotationExtract-extracted", 3, 11, 0, (int) ((unsigned long) &s.extracted - (unsigned long) &s));  }

  {
    struct FaceEyeLocation s;

    bindInt(script, "FaceEyeLocation-struct", sizeof(s));
    bindIntListva(script, "FaceEyeLocation-x1", 3, 5, 0, (int) ((unsigned long) &s.x1 - (unsigned long) &s));    bindIntListva(script, "FaceEyeLocation-y1", 3, 5, 0, (int) ((unsigned long) &s.y1 - (unsigned long) &s));    bindIntListva(script, "FaceEyeLocation-x2", 3, 5, 0, (int) ((unsigned long) &s.x2 - (unsigned long) &s));    bindIntListva(script, "FaceEyeLocation-y2", 3, 5, 0, (int) ((unsigned long) &s.y2 - (unsigned long) &s));    bindIntListva(script, "FaceEyeLocation-leftx", 3, 5, 0, (int) ((unsigned long) &s.leftx - (unsigned long) &s));    bindIntListva(script, "FaceEyeLocation-lefty", 3, 5, 0, (int) ((unsigned long) &s.lefty - (unsigned long) &s));    bindIntListva(script, "FaceEyeLocation-rightx", 3, 5, 0, (int) ((unsigned long) &s.rightx - (unsigned long) &s));    bindIntListva(script, "FaceEyeLocation-righty", 3, 5, 0, (int) ((unsigned long) &s.righty - (unsigned long) &s));    bindIntListva(script, "FaceEyeLocation-left", 3, 5, 0, (int) ((unsigned long) &s.left - (unsigned long) &s));    bindIntListva(script, "FaceEyeLocation-right", 3, 5, 0, (int) ((unsigned long) &s.right - (unsigned long) &s));  }


}

/**************************************************************************/

/* ---------------------------------------------------------------------- */
Value *isis_SearchEye(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int SearchEye(int width, int height, unsigned char *buffer, int eyeWidthGuess, int leftEye, int *x, int *y); */

  checkCount(7, "width, height, buffer, eyeWidthGuess, leftEye, x, y");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkInt(3, "eyeWidthGuess");
  checkInt(4, "leftEye");
  checkAddr(5, "x");
  checkAddr(6, "y");

  return newInt( SearchEye ( (int) getInt(argv[0]),
                             (int) getInt(argv[1]),
                             (unsigned char *) getAddr(argv[2]),
                             (int) getInt(argv[3]),
                             (int) getInt(argv[4]),
                             (int *) getAddr(argv[5]),
                             (int *) getAddr(argv[6]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Informedia_FindFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Informedia_FindFaces(int width, int height, unsigned char *buffer, struct FaceLocation **locs); */

  checkCount(4, "width, height, buffer, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "locs");

  return newInt( Informedia_FindFaces ( (int) getInt(argv[0]),
                                        (int) getInt(argv[1]),
                                        (unsigned char *) getAddr(argv[2]),
                                        (struct FaceLocation **) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Informedia_FindFacesRGBA(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Informedia_FindFacesRGBA(int width, int height, unsigned char *buffer, struct FaceLocation **locs); */

  checkCount(4, "width, height, buffer, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "locs");

  return newInt( Informedia_FindFacesRGBA ( (int) getInt(argv[0]),
                                            (int) getInt(argv[1]),
                                            (unsigned char *) getAddr(argv[2]),
                                            (struct FaceLocation **) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Informedia_FindFacesOrientation(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Informedia_FindFacesOrientation( int width, int height, unsigned char *buffer, struct FaceLocationOrientation **locs); */

  checkCount(4, "width, height, buffer, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "locs");

  return newInt( Informedia_FindFacesOrientation ( (int) getInt(argv[0]),
                                                   (int) getInt(argv[1]),
                                                   (unsigned char *) getAddr(argv[2]),
                                                   (struct FaceLocationOrientation **) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Informedia_FindFacesAllCandidates(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /*  extern void Informedia_FindFacesAllCandidates(int width, int height, unsigned char *buffer, int verificationThreshold, Cfunc *cb); */

  checkCount(5, "width, height, buffer, verificationThreshold, cb");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkInt(3, "verificationThreshold");
  checkAddr(4, "cb");

  Informedia_FindFacesAllCandidates ( (int) getInt(argv[0]),
                                      (int) getInt(argv[1]),
                                      (unsigned char *) getAddr(argv[2]),
                                      (int) getInt(argv[3]),
                                      getAddr(argv[4]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_Informedia_FindFacesGray(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Informedia_FindFacesGray(int width, int height, unsigned char *buffer, struct FaceLocation **locs); */

  checkCount(4, "width, height, buffer, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "locs");

  return newInt( Informedia_FindFacesGray ( (int) getInt(argv[0]),
                                            (int) getInt(argv[1]),
                                            (unsigned char *) getAddr(argv[2]),
                                            (struct FaceLocation **) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Informedia_FindFacesOrientationGray(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Informedia_FindFacesOrientationGray(int width, int height, unsigned char *buffer, struct FaceLocationOrientation **locs); */

  checkCount(4, "width, height, buffer, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "locs");

  return newInt( Informedia_FindFacesOrientationGray ( (int) getInt(argv[0]),
                                                       (int) getInt(argv[1]),
                                                       (unsigned char *) getAddr(argv[2]),
                                                       (struct FaceLocationOrientation **) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Xavier_FindAllFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Xavier_FindAllFaces(int width, int height, unsigned char *buffer, struct FaceLocation **locs); */

  checkCount(4, "width, height, buffer, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "locs");

  return newInt( Xavier_FindAllFaces ( (int) getInt(argv[0]),
                                       (int) getInt(argv[1]),
                                       (unsigned char *) getAddr(argv[2]),
                                       (struct FaceLocation **) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Xavier_FindAllFacesColor(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Xavier_FindAllFacesColor(int width, int height, unsigned char *buffer, struct FaceLocation **locs); */

  checkCount(4, "width, height, buffer, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "locs");

  return newInt( Xavier_FindAllFacesColor ( (int) getInt(argv[0]),
                                            (int) getInt(argv[1]),
                                            (unsigned char *) getAddr(argv[2]),
                                            (struct FaceLocation **) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Xavier_FindOneFace(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Xavier_FindOneFace(int width, int height, unsigned char *buffer, int minX, int maxX, int minY, int maxY, int minSize, int maxSize, int optimizationFlags, unsigned char *prevImage, int changeThreshold, struct FaceLocation *loc); */

  checkCount(13, "width, height, buffer, minX, maxX, minY, maxY, minSize, maxSize, optimizationFlags, prevImage, changeThreshold, loc");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkInt(3, "minX");
  checkInt(4, "maxX");
  checkInt(5, "minY");
  checkInt(6, "maxY");
  checkInt(7, "minSize");
  checkInt(8, "maxSize");
  checkInt(9, "optimizationFlags");
  checkAddr(10, "prevImage");
  checkInt(11, "changeThreshold");
  checkAddr(12, "loc");

  return newInt( Xavier_FindOneFace ( (int) getInt(argv[0]),
                                      (int) getInt(argv[1]),
                                      (unsigned char *) getAddr(argv[2]),
                                      (int) getInt(argv[3]),
                                      (int) getInt(argv[4]),
                                      (int) getInt(argv[5]),
                                      (int) getInt(argv[6]),
                                      (int) getInt(argv[7]),
                                      (int) getInt(argv[8]),
                                      (int) getInt(argv[9]),
                                      (unsigned char *) getAddr(argv[10]),
                                      (int) getInt(argv[11]),
                                      (struct FaceLocation *) getAddr(argv[12]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Xavier_FindOneFaceColor(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Xavier_FindOneFaceColor(int width, int height, unsigned char *buffer, int minX, int maxX, int minY, int maxY, int minSize, int maxSize, int optimizationFlags, unsigned char *prevImage, int changeThreshold, struct FaceLocation *loc); */

  checkCount(13, "width, height, buffer, minX, maxX, minY, maxY, minSize, maxSize, optimizationFlags, prevImage, changeThreshold, loc");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkInt(3, "minX");
  checkInt(4, "maxX");
  checkInt(5, "minY");
  checkInt(6, "maxY");
  checkInt(7, "minSize");
  checkInt(8, "maxSize");
  checkInt(9, "optimizationFlags");
  checkAddr(10, "prevImage");
  checkInt(11, "changeThreshold");
  checkAddr(12, "loc");

  return newInt( Xavier_FindOneFaceColor ( (int) getInt(argv[0]),
                                           (int) getInt(argv[1]),
                                           (unsigned char *) getAddr(argv[2]),
                                           (int) getInt(argv[3]),
                                           (int) getInt(argv[4]),
                                           (int) getInt(argv[5]),
                                           (int) getInt(argv[6]),
                                           (int) getInt(argv[7]),
                                           (int) getInt(argv[8]),
                                           (int) getInt(argv[9]),
                                           (unsigned char *) getAddr(argv[10]),
                                           (int) getInt(argv[11]),
                                           (struct FaceLocation *) getAddr(argv[12]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Slow_FindAllFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Slow_FindAllFaces(int width, int height, unsigned char *buffer, int mode, struct FaceLocation **locs); */

  checkCount(5, "width, height, buffer, mode, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkInt(3, "mode");
  checkAddr(4, "locs");

  return newInt( Slow_FindAllFaces ( (int) getInt(argv[0]),
                                     (int) getInt(argv[1]),
                                     (unsigned char *) getAddr(argv[2]),
                                     (int) getInt(argv[3]),
                                     (struct FaceLocation **) getAddr(argv[4]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Track_FindAllFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Track_FindAllFaces(int width, int height, unsigned char *buffer, struct FaceEyeLocation **locs); */

  checkCount(4, "width, height, buffer, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "locs");

  return newInt( Track_FindAllFaces ( (int) getInt(argv[0]),
                                      (int) getInt(argv[1]),
                                      (unsigned char *) getAddr(argv[2]),
                                      (struct FaceEyeLocation **) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Track_FindAllFacesRegion(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Track_FindAllFacesRegion(int width, int height, unsigned char *buffer, int minX, int maxX, int minY, int maxY, int minSize, int maxSize, struct FaceEyeLocation **locs); */

  checkCount(10, "width, height, buffer, minX, maxX, minY, maxY, minSize, maxSize, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkInt(3, "minX");
  checkInt(4, "maxX");
  checkInt(5, "minY");
  checkInt(6, "maxY");
  checkInt(7, "minSize");
  checkInt(8, "maxSize");
  checkAddr(9, "locs");

  return newInt( Track_FindAllFacesRegion ( (int) getInt(argv[0]),
                                            (int) getInt(argv[1]),
                                            (unsigned char *) getAddr(argv[2]),
                                            (int) getInt(argv[3]),
                                            (int) getInt(argv[4]),
                                            (int) getInt(argv[5]),
                                            (int) getInt(argv[6]),
                                            (int) getInt(argv[7]),
                                            (int) getInt(argv[8]),
                                            (struct FaceEyeLocation **) getAddr(argv[9]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Siemens_FindAllFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Siemens_FindAllFaces(int width, int height, unsigned char *buffer, unsigned char *motionMask, struct FaceEyeLocation **locs); */

  checkCount(5, "width, height, buffer, motionMask, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "motionMask");
  checkAddr(4, "locs");

  return newInt( Siemens_FindAllFaces ( (int) getInt(argv[0]),
                                        (int) getInt(argv[1]),
                                        (unsigned char *) getAddr(argv[2]),
                                        (unsigned char *) getAddr(argv[3]),
                                        (struct FaceEyeLocation **) getAddr(argv[4]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Astro_FindAllFaces(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Astro_FindAllFaces(int width, int height, unsigned char *buffer, struct FaceLocation **locs); */

  checkCount(4, "width, height, buffer, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "locs");

  return newInt( Astro_FindAllFaces ( (int) getInt(argv[0]),
                                      (int) getInt(argv[1]),
                                      (unsigned char *) getAddr(argv[2]),
                                      (struct FaceLocation **) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Rotation_FindAllFacesSlow(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Rotation_FindAllFacesSlow(int width, int height, unsigned char *buffer, struct FaceLocationRotation **locs); */

  checkCount(4, "width, height, buffer, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkAddr(3, "locs");

  return newInt( Rotation_FindAllFacesSlow ( (int) getInt(argv[0]),
                                             (int) getInt(argv[1]),
                                             (unsigned char *) getAddr(argv[2]),
                                             (struct FaceLocationRotation **) getAddr(argv[3]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_Rotation_FindAllFacesSlowExtract(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern int Rotation_FindAllFacesSlowExtract(int width, int height, unsigned char *buffer, double threshold, int arbThresold, struct FaceLocationRotationExtract **locs); */

  checkCount(6, "width, height, buffer, threshold, arbThresold, locs");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkReal(3, "threshold");
  checkInt(4, "arbThresold");
  checkAddr(5, "locs");

  return newInt( Rotation_FindAllFacesSlowExtract ( (int) getInt(argv[0]),
                                                    (int) getInt(argv[1]),
                                                    (unsigned char *) getAddr(argv[2]),
                                                    (double) getReal(argv[3]),
                                                    (int) getInt(argv[4]),
                                                    (struct FaceLocationRotationExtract **) getAddr(argv[5]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_BroadenColorMask(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern void BroadenColorMask(double amount); */

  checkCount(1, "amount");

  checkReal(0, "amount");

  BroadenColorMask ( (double) getReal(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_UpdateColorMaskFromBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* extern void UpdateColorMaskFromBuffer(int width, int height, unsigned char *buffer, int x1, int y1, int x2, int y2, double amount); */

  checkCount(8, "width, height, buffer, x1, y1, x2, y2, amount");

  checkInt(0, "width");
  checkInt(1, "height");
  checkAddr(2, "buffer");
  checkInt(3, "x1");
  checkInt(4, "y1");
  checkInt(5, "x2");
  checkInt(6, "y2");
  checkReal(7, "amount");

  UpdateColorMaskFromBuffer ( (int) getInt(argv[0]),
                              (int) getInt(argv[1]),
                              (unsigned char *) getAddr(argv[2]),
                              (int) getInt(argv[3]),
                              (int) getInt(argv[4]),
                              (int) getInt(argv[5]),
                              (int) getInt(argv[6]),
                              (double) getReal(argv[7]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_LoadGifToBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* unsigned char *LoadGifToBuffer(char *filename, int *width, int *height); */

  int len;
  char *filename;
  Value *retval;

  checkCount(3, "filename, width, height");

  checkString(0, "filename");
  checkAddr(1, "width");
  checkAddr(2, "height");

  len = Listsize(argv[0]) + 1;
  filename = newStr(len);
  if(filename) getString(argv[0], filename, len);

  retval = newAddr( (void *) LoadGifToBuffer ( (char *) filename,
                                               (int *) getAddr(argv[1]),
                                               (int *) getAddr(argv[2]) ) );

  freeStr(filename);

  return retval;
}

/* ---------------------------------------------------------------------- */
Value *isis_LoadPgmToBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* unsigned char *LoadPgmToBuffer(char *filename, int *width, int *height); */

  int len;
  char *filename;
  Value *retval;

  checkCount(3, "filename, width, height");

  checkString(0, "filename");
  checkAddr(1, "width");
  checkAddr(2, "height");

  len = Listsize(argv[0]) + 1;
  filename = newStr(len);
  if(filename) getString(argv[0], filename, len);

  retval = newAddr( (void *) LoadPgmToBuffer ( (char *) filename,
                                               (int *) getAddr(argv[1]),
                                               (int *) getAddr(argv[2]) ) );

  freeStr(filename);

  return retval;
}

/* ---------------------------------------------------------------------- */
Value *isis_LoadPpmToBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* unsigned char *LoadPpmToBuffer(char *filename, int *width, int *height); */

  int len;
  char *filename;
  Value *retval;

  checkCount(3, "filename, width, height");

  checkString(0, "filename");
  checkAddr(1, "width");
  checkAddr(2, "height");

  len = Listsize(argv[0]) + 1;
  filename = newStr(len);
  if(filename) getString(argv[0], filename, len);

  retval = newAddr( (void *) LoadPpmToBuffer ( (char *) filename,
                                               (int *) getAddr(argv[1]),
                                               (int *) getAddr(argv[2]) ) );

  freeStr(filename);

  return retval;
}

/* ---------------------------------------------------------------------- */
Value *isis_LoadPgmStreamToBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* unsigned char *LoadPgmStreamToBuffer(FILE *inf, int *width, int *height); */

  checkCount(3, "inf, width, height");

  checkAddr(0, "inf");
  checkAddr(1, "width");
  checkAddr(2, "height");

  return newAddr( (void *) LoadPgmStreamToBuffer ( (FILE *) getAddr(argv[0]),
                                                   (int *) getAddr(argv[1]),
                                                   (int *) getAddr(argv[2]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_LoadPpmStreamToBuffer(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* unsigned char *LoadPpmStreamToBuffer(FILE *inf, int *width, int *height); */

  checkCount(3, "inf, width, height");

  checkAddr(0, "inf");
  checkAddr(1, "width");
  checkAddr(2, "height");

  return newAddr( (void *) LoadPpmStreamToBuffer ( (FILE *) getAddr(argv[0]),
                                                   (int *) getAddr(argv[1]),
                                                   (int *) getAddr(argv[2]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_SetDataPath(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void SetDataPath(char *argv0); */

  int len;
  char *argv0;

  checkCount(1, "argv0");

  checkString(0, "argv0");

  len = Listsize(argv[0]) + 1;
  argv0 = newStr(len);
  if(argv0) getString(argv[0], argv0, len);

  SetDataPath ( (char *) argv0 );

  freeStr(argv0);

  return NullValue;
}


/**************************************************************************/

/* ---------------------------------------------------------------------- */
Value *isis_cmuface_update_callback_slot(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  Procedure **procaddr;
  
  checkCount(2, "callback slot, callback procedure");
  checkAddr(0, "callback slot");
  if(!isNull(argv[1])) checkProc(1, "callback procedure");
  
  procaddr = (Procedure **) getAddr(argv[0]);
  if(*procaddr != NULL) freeProcedure(*procaddr);
  if(isNull(argv[1])) *procaddr = NULL;
  else *procaddr = referProcedure(getProc(argv[1]));
  
  return NullValue;
}

/* ---------------------------------------------------------------------- */
int *isis_Informedia_CandidateCallback(double candidateRating, int xc, int yc, int sc, double verifyRating1, int x1, int y1, int s1, double verifyRating2, int x2, int y2, int s2)
{
  int i;
  Value **argv, *val;
  int * retval;

  argv = (Value **) newPtrArray(12);

  argv[0] = newReal(candidateRating);
  argv[1] = newInt(xc);
  argv[2] = newInt(yc);
  argv[3] = newInt(sc);
  argv[4] = newReal(verifyRating1);
  argv[5] = newInt(x1);
  argv[6] = newInt(y1);
  argv[7] = newInt(s1);
  argv[8] = newReal(verifyRating2);
  argv[9] = newInt(x2);
  argv[10] = newInt(y2);
  argv[11] = newInt(s2);

  val = applyProcedure(localscript, isis_Informedia_CandidateCallback_proc, 12, argv);

  for(i = 0; i < 12; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  retval = getAddr(val);
  freeValue(val);

  return retval;
}

