/**************************************************************************/
/* Isis glut interface library 
   automatically generated by the Isis header file conversion utility
   written by Stefan Agamanolis, February 1998 */

#include <stdlib.h>
#include <stdio.h>
#include <isis.h>

#include "isis_glut.h"

#if defined(WIN32)
#include <windows.h>
#endif
#include <GL/glut.h>

/**************************************************************************/

static Script *localscript;

Value *isis_glutInit(Script *script, char *proc_name, int call_data, 
                     int argc, Value **argv);
Value *isis_glutInitDisplayMode(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv);
Value *isis_glutInitWindowPosition(Script *script, char *proc_name, int call_data, 
                                   int argc, Value **argv);
Value *isis_glutInitWindowSize(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv);
Value *isis_glutMainLoop(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv);
Value *isis_glutCreateWindow(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv);
Value *isis_glutCreateSubWindow(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv);
Value *isis_glutDestroyWindow(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv);
Value *isis_glutPostRedisplay(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv);
Value *isis_glutSwapBuffers(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutGetWindow(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutSetWindow(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutSetWindowTitle(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv);
Value *isis_glutSetIconTitle(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv);
Value *isis_glutPositionWindow(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv);
Value *isis_glutReshapeWindow(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv);
Value *isis_glutPopWindow(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutPushWindow(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutIconifyWindow(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv);
Value *isis_glutShowWindow(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutHideWindow(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutFullScreen(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutSetCursor(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutEstablishOverlay(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv);
Value *isis_glutRemoveOverlay(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv);
Value *isis_glutUseLayer(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv);
Value *isis_glutPostOverlayRedisplay(Script *script, char *proc_name, int call_data, 
                                     int argc, Value **argv);
Value *isis_glutShowOverlay(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutHideOverlay(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutCreateMenu(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutDestroyMenu(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutGetMenu(Script *script, char *proc_name, int call_data, 
                        int argc, Value **argv);
Value *isis_glutSetMenu(Script *script, char *proc_name, int call_data, 
                        int argc, Value **argv);
Value *isis_glutAddMenuEntry(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv);
Value *isis_glutAddSubMenu(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutChangeToMenuEntry(Script *script, char *proc_name, int call_data, 
                                  int argc, Value **argv);
Value *isis_glutChangeToSubMenu(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv);
Value *isis_glutRemoveMenuItem(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv);
Value *isis_glutAttachMenu(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutDetachMenu(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutDisplayFunc(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutReshapeFunc(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutKeyboardFunc(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv);
Value *isis_glutMouseFunc(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutMotionFunc(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutPassiveMotionFunc(Script *script, char *proc_name, int call_data, 
                                  int argc, Value **argv);
Value *isis_glutEntryFunc(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutVisibilityFunc(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv);
Value *isis_glutIdleFunc(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv);
Value *isis_glutTimerFunc(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutMenuStateFunc(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv);
Value *isis_glutSpecialFunc(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutSpaceballMotionFunc(Script *script, char *proc_name, int call_data, 
                                    int argc, Value **argv);
Value *isis_glutSpaceballRotateFunc(Script *script, char *proc_name, int call_data, 
                                    int argc, Value **argv);
Value *isis_glutSpaceballButtonFunc(Script *script, char *proc_name, int call_data, 
                                    int argc, Value **argv);
Value *isis_glutButtonBoxFunc(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv);
Value *isis_glutDialsFunc(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutTabletMotionFunc(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv);
Value *isis_glutTabletButtonFunc(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv);
Value *isis_glutMenuStatusFunc(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv);
Value *isis_glutOverlayDisplayFunc(Script *script, char *proc_name, int call_data, 
                                   int argc, Value **argv);
Value *isis_glutSetColor(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv);
Value *isis_glutGetColor(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv);
Value *isis_glutCopyColormap(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv);
Value *isis_glutGet(Script *script, char *proc_name, int call_data, 
                    int argc, Value **argv);
Value *isis_glutDeviceGet(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutExtensionSupported(Script *script, char *proc_name, int call_data, 
                                   int argc, Value **argv);
Value *isis_glutGetModifiers(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv);
Value *isis_glutLayerGet(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv);
Value *isis_glutBitmapCharacter(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv);
Value *isis_glutBitmapWidth(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutStrokeCharacter(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv);
Value *isis_glutStrokeWidth(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutWireSphere(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutSolidSphere(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutWireCone(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv);
Value *isis_glutSolidCone(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutWireCube(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv);
Value *isis_glutSolidCube(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutWireTorus(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv);
Value *isis_glutSolidTorus(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutWireDodecahedron(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv);
Value *isis_glutSolidDodecahedron(Script *script, char *proc_name, int call_data, 
                                  int argc, Value **argv);
Value *isis_glutWireTeapot(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv);
Value *isis_glutSolidTeapot(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv);
Value *isis_glutWireOctahedron(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv);
Value *isis_glutSolidOctahedron(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv);
Value *isis_glutWireTetrahedron(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv);
Value *isis_glutSolidTetrahedron(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv);
Value *isis_glutWireIcosahedron(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv);
Value *isis_glutSolidIcosahedron(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv);

/**************************************************************************/

Value *isis_glut_update_callback_slot(Script *script, char *proc_name, int call_data,
                                      int argc, Value **argv);

void glut_create_menu(int a);
void glut_display(void);
void glut_reshape(int width, int height);
void glut_keyboard(unsigned char key, int x, int y);
void glut_mouse(int button, int state, int x, int y);
void glut_motion(int x, int y);
void glut_passive_motion(int x, int y);
void glut_entry(int state);
void glut_visibility(int state);
void glut_idle(void);
void glut_timer(int value);
void glut_menu_state(int state);
void glut_special(int key, int x, int y);
void glut_spaceball_motion(int x, int y, int z);
void glut_spaceball_rotate(int x, int y, int z);
void glut_spaceball_button(int button, int state);
void glut_button_box(int button, int state);
void glut_dials(int dial, int value);
void glut_tablet_motion(int x, int y);
void glut_tablet_button(int button, int state, int x, int y);
void glut_menu_status(int status, int x, int y);
void glut_overlay_display(void);

static Procedure *glut_create_menu_proc = NULL;
static Procedure *glut_display_proc = NULL;
static Procedure *glut_reshape_proc = NULL;
static Procedure *glut_keyboard_proc = NULL;
static Procedure *glut_mouse_proc = NULL;
static Procedure *glut_motion_proc = NULL;
static Procedure *glut_passive_motion_proc = NULL;
static Procedure *glut_entry_proc = NULL;
static Procedure *glut_visibility_proc = NULL;
static Procedure *glut_idle_proc = NULL;
static Procedure *glut_timer_proc = NULL;
static Procedure *glut_menu_state_proc = NULL;
static Procedure *glut_special_proc = NULL;
static Procedure *glut_spaceball_motion_proc = NULL;
static Procedure *glut_spaceball_rotate_proc = NULL;
static Procedure *glut_spaceball_button_proc = NULL;
static Procedure *glut_button_box_proc = NULL;
static Procedure *glut_dials_proc = NULL;
static Procedure *glut_tablet_motion_proc = NULL;
static Procedure *glut_tablet_button_proc = NULL;
static Procedure *glut_menu_status_proc = NULL;
static Procedure *glut_overlay_display_proc = NULL;

/**************************************************************************/

void bind_glut_library(Script *script)
{
  bindBool(script, "isis_glut", 1);

  localscript = script;

  bindCfunc(script, "glutInit", isis_glutInit, 0);
  bindCfunc(script, "glutInitDisplayMode", isis_glutInitDisplayMode, 0);
  bindCfunc(script, "glutInitWindowPosition", isis_glutInitWindowPosition, 0);
  bindCfunc(script, "glutInitWindowSize", isis_glutInitWindowSize, 0);
  bindCfunc(script, "glutMainLoop", isis_glutMainLoop, 0);
  bindCfunc(script, "glutCreateWindow", isis_glutCreateWindow, 0);
  bindCfunc(script, "glutCreateSubWindow", isis_glutCreateSubWindow, 0);
  bindCfunc(script, "glutDestroyWindow", isis_glutDestroyWindow, 0);
  bindCfunc(script, "glutPostRedisplay", isis_glutPostRedisplay, 0);
  bindCfunc(script, "glutSwapBuffers", isis_glutSwapBuffers, 0);
  bindCfunc(script, "glutGetWindow", isis_glutGetWindow, 0);
  bindCfunc(script, "glutSetWindow", isis_glutSetWindow, 0);
  bindCfunc(script, "glutSetWindowTitle", isis_glutSetWindowTitle, 0);
  bindCfunc(script, "glutSetIconTitle", isis_glutSetIconTitle, 0);
  bindCfunc(script, "glutPositionWindow", isis_glutPositionWindow, 0);
  bindCfunc(script, "glutReshapeWindow", isis_glutReshapeWindow, 0);
  bindCfunc(script, "glutPopWindow", isis_glutPopWindow, 0);
  bindCfunc(script, "glutPushWindow", isis_glutPushWindow, 0);
  bindCfunc(script, "glutIconifyWindow", isis_glutIconifyWindow, 0);
  bindCfunc(script, "glutShowWindow", isis_glutShowWindow, 0);
  bindCfunc(script, "glutHideWindow", isis_glutHideWindow, 0);
  bindCfunc(script, "glutFullScreen", isis_glutFullScreen, 0);
  bindCfunc(script, "glutSetCursor", isis_glutSetCursor, 0);
  bindCfunc(script, "glutEstablishOverlay", isis_glutEstablishOverlay, 0);
  bindCfunc(script, "glutRemoveOverlay", isis_glutRemoveOverlay, 0);
  bindCfunc(script, "glutUseLayer", isis_glutUseLayer, 0);
  bindCfunc(script, "glutPostOverlayRedisplay", isis_glutPostOverlayRedisplay, 0);
  bindCfunc(script, "glutShowOverlay", isis_glutShowOverlay, 0);
  bindCfunc(script, "glutHideOverlay", isis_glutHideOverlay, 0);
  bindCfunc(script, "glutCreateMenu", isis_glutCreateMenu, 0);
  bindCfunc(script, "glutDestroyMenu", isis_glutDestroyMenu, 0);
  bindCfunc(script, "glutGetMenu", isis_glutGetMenu, 0);
  bindCfunc(script, "glutSetMenu", isis_glutSetMenu, 0);
  bindCfunc(script, "glutAddMenuEntry", isis_glutAddMenuEntry, 0);
  bindCfunc(script, "glutAddSubMenu", isis_glutAddSubMenu, 0);
  bindCfunc(script, "glutChangeToMenuEntry", isis_glutChangeToMenuEntry, 0);
  bindCfunc(script, "glutChangeToSubMenu", isis_glutChangeToSubMenu, 0);
  bindCfunc(script, "glutRemoveMenuItem", isis_glutRemoveMenuItem, 0);
  bindCfunc(script, "glutAttachMenu", isis_glutAttachMenu, 0);
  bindCfunc(script, "glutDetachMenu", isis_glutDetachMenu, 0);
  bindCfunc(script, "glutDisplayFunc", isis_glutDisplayFunc, 0);
  bindCfunc(script, "glutReshapeFunc", isis_glutReshapeFunc, 0);
  bindCfunc(script, "glutKeyboardFunc", isis_glutKeyboardFunc, 0);
  bindCfunc(script, "glutMouseFunc", isis_glutMouseFunc, 0);
  bindCfunc(script, "glutMotionFunc", isis_glutMotionFunc, 0);
  bindCfunc(script, "glutPassiveMotionFunc", isis_glutPassiveMotionFunc, 0);
  bindCfunc(script, "glutEntryFunc", isis_glutEntryFunc, 0);
  bindCfunc(script, "glutVisibilityFunc", isis_glutVisibilityFunc, 0);
  bindCfunc(script, "glutIdleFunc", isis_glutIdleFunc, 0);
  bindCfunc(script, "glutTimerFunc", isis_glutTimerFunc, 0);
  bindCfunc(script, "glutMenuStateFunc", isis_glutMenuStateFunc, 0);
  bindCfunc(script, "glutSpecialFunc", isis_glutSpecialFunc, 0);
  bindCfunc(script, "glutSpaceballMotionFunc", isis_glutSpaceballMotionFunc, 0);
  bindCfunc(script, "glutSpaceballRotateFunc", isis_glutSpaceballRotateFunc, 0);
  bindCfunc(script, "glutSpaceballButtonFunc", isis_glutSpaceballButtonFunc, 0);
  bindCfunc(script, "glutButtonBoxFunc", isis_glutButtonBoxFunc, 0);
  bindCfunc(script, "glutDialsFunc", isis_glutDialsFunc, 0);
  bindCfunc(script, "glutTabletMotionFunc", isis_glutTabletMotionFunc, 0);
  bindCfunc(script, "glutTabletButtonFunc", isis_glutTabletButtonFunc, 0);
  bindCfunc(script, "glutMenuStatusFunc", isis_glutMenuStatusFunc, 0);
  bindCfunc(script, "glutOverlayDisplayFunc", isis_glutOverlayDisplayFunc, 0);
  bindCfunc(script, "glutSetColor", isis_glutSetColor, 0);
  bindCfunc(script, "glutGetColor", isis_glutGetColor, 0);
  bindCfunc(script, "glutCopyColormap", isis_glutCopyColormap, 0);
  bindCfunc(script, "glutGet", isis_glutGet, 0);
  bindCfunc(script, "glutDeviceGet", isis_glutDeviceGet, 0);
  bindCfunc(script, "glutExtensionSupported", isis_glutExtensionSupported, 0);
  bindCfunc(script, "glutGetModifiers", isis_glutGetModifiers, 0);
  bindCfunc(script, "glutLayerGet", isis_glutLayerGet, 0);
  bindCfunc(script, "glutBitmapCharacter", isis_glutBitmapCharacter, 0);
  bindCfunc(script, "glutBitmapWidth", isis_glutBitmapWidth, 0);
  bindCfunc(script, "glutStrokeCharacter", isis_glutStrokeCharacter, 0);
  bindCfunc(script, "glutStrokeWidth", isis_glutStrokeWidth, 0);
  bindCfunc(script, "glutWireSphere", isis_glutWireSphere, 0);
  bindCfunc(script, "glutSolidSphere", isis_glutSolidSphere, 0);
  bindCfunc(script, "glutWireCone", isis_glutWireCone, 0);
  bindCfunc(script, "glutSolidCone", isis_glutSolidCone, 0);
  bindCfunc(script, "glutWireCube", isis_glutWireCube, 0);
  bindCfunc(script, "glutSolidCube", isis_glutSolidCube, 0);
  bindCfunc(script, "glutWireTorus", isis_glutWireTorus, 0);
  bindCfunc(script, "glutSolidTorus", isis_glutSolidTorus, 0);
  bindCfunc(script, "glutWireDodecahedron", isis_glutWireDodecahedron, 0);
  bindCfunc(script, "glutSolidDodecahedron", isis_glutSolidDodecahedron, 0);
  bindCfunc(script, "glutWireTeapot", isis_glutWireTeapot, 0);
  bindCfunc(script, "glutSolidTeapot", isis_glutSolidTeapot, 0);
  bindCfunc(script, "glutWireOctahedron", isis_glutWireOctahedron, 0);
  bindCfunc(script, "glutSolidOctahedron", isis_glutSolidOctahedron, 0);
  bindCfunc(script, "glutWireTetrahedron", isis_glutWireTetrahedron, 0);
  bindCfunc(script, "glutSolidTetrahedron", isis_glutSolidTetrahedron, 0);
  bindCfunc(script, "glutWireIcosahedron", isis_glutWireIcosahedron, 0);
  bindCfunc(script, "glutSolidIcosahedron", isis_glutSolidIcosahedron, 0);

  bindCfunc(script, "update-glut-callback-slot", isis_glut_update_callback_slot, 0);

  bindAddr(script, "glut_create_menu", glut_create_menu);
  bindAddr(script, "glut_display", glut_display);
  bindAddr(script, "glut_reshape", glut_reshape);
  bindAddr(script, "glut_keyboard", glut_keyboard);
  bindAddr(script, "glut_mouse", glut_mouse);
  bindAddr(script, "glut_motion", glut_motion);
  bindAddr(script, "glut_passive_motion", glut_passive_motion);
  bindAddr(script, "glut_entry", glut_entry);
  bindAddr(script, "glut_visibility", glut_visibility);
  bindAddr(script, "glut_idle", glut_idle);
  bindAddr(script, "glut_timer", glut_timer);
  bindAddr(script, "glut_menu_state", glut_menu_state);
  bindAddr(script, "glut_special", glut_special);
  bindAddr(script, "glut_spaceball_motion", glut_spaceball_motion);
  bindAddr(script, "glut_spaceball_rotate", glut_spaceball_rotate);
  bindAddr(script, "glut_spaceball_button", glut_spaceball_button);
  bindAddr(script, "glut_button_box", glut_button_box);
  bindAddr(script, "glut_dials", glut_dials);
  bindAddr(script, "glut_tablet_motion", glut_tablet_motion);
  bindAddr(script, "glut_tablet_button", glut_tablet_button);
  bindAddr(script, "glut_menu_status", glut_menu_status);
  bindAddr(script, "glut_overlay_display", glut_overlay_display);

  bindAddr(script, "glut_create_menu_slot", &glut_create_menu_proc);
  bindAddr(script, "glut_display_slot", &glut_display_proc);
  bindAddr(script, "glut_reshape_slot", &glut_reshape_proc);
  bindAddr(script, "glut_keyboard_slot", &glut_keyboard_proc);
  bindAddr(script, "glut_mouse_slot", &glut_mouse_proc);
  bindAddr(script, "glut_motion_slot", &glut_motion_proc);
  bindAddr(script, "glut_passive_motion_slot", &glut_passive_motion_proc);
  bindAddr(script, "glut_entry_slot", &glut_entry_proc);
  bindAddr(script, "glut_visibility_slot", &glut_visibility_proc);
  bindAddr(script, "glut_idle_slot", &glut_idle_proc);
  bindAddr(script, "glut_timer_slot", &glut_timer_proc);
  bindAddr(script, "glut_menu_state_slot", &glut_menu_state_proc);
  bindAddr(script, "glut_special_slot", &glut_special_proc);
  bindAddr(script, "glut_spaceball_motion_slot", &glut_spaceball_motion_proc);
  bindAddr(script, "glut_spaceball_rotate_slot", &glut_spaceball_rotate_proc);
  bindAddr(script, "glut_spaceball_button_slot", &glut_spaceball_button_proc);
  bindAddr(script, "glut_button_box_slot", &glut_button_box_proc);
  bindAddr(script, "glut_dials_slot", &glut_dials_proc);
  bindAddr(script, "glut_tablet_motion_slot", &glut_tablet_motion_proc);
  bindAddr(script, "glut_tablet_button_slot", &glut_tablet_button_proc);
  bindAddr(script, "glut_menu_status_slot", &glut_menu_status_proc);
  bindAddr(script, "glut_overlay_display_slot", &glut_overlay_display_proc);

  bindInt(script, "GLUT_API_VERSION", GLUT_API_VERSION);
  bindInt(script, "GLUT_XLIB_IMPLEMENTATION", GLUT_XLIB_IMPLEMENTATION);
  bindInt(script, "GLUT_RGB", GLUT_RGB);
  bindInt(script, "GLUT_RGBA", GLUT_RGBA);
  bindInt(script, "GLUT_INDEX", GLUT_INDEX);
  bindInt(script, "GLUT_SINGLE", GLUT_SINGLE);
  bindInt(script, "GLUT_DOUBLE", GLUT_DOUBLE);
  bindInt(script, "GLUT_ACCUM", GLUT_ACCUM);
  bindInt(script, "GLUT_ALPHA", GLUT_ALPHA);
  bindInt(script, "GLUT_DEPTH", GLUT_DEPTH);
  bindInt(script, "GLUT_STENCIL", GLUT_STENCIL);
  bindInt(script, "GLUT_MULTISAMPLE", GLUT_MULTISAMPLE);
  bindInt(script, "GLUT_STEREO", GLUT_STEREO);
  bindInt(script, "GLUT_LUMINANCE", GLUT_LUMINANCE);
  bindInt(script, "GLUT_LEFT_BUTTON", GLUT_LEFT_BUTTON);
  bindInt(script, "GLUT_MIDDLE_BUTTON", GLUT_MIDDLE_BUTTON);
  bindInt(script, "GLUT_RIGHT_BUTTON", GLUT_RIGHT_BUTTON);
  bindInt(script, "GLUT_DOWN", GLUT_DOWN);
  bindInt(script, "GLUT_UP", GLUT_UP);
  bindInt(script, "GLUT_KEY_F1", GLUT_KEY_F1);
  bindInt(script, "GLUT_KEY_F2", GLUT_KEY_F2);
  bindInt(script, "GLUT_KEY_F3", GLUT_KEY_F3);
  bindInt(script, "GLUT_KEY_F4", GLUT_KEY_F4);
  bindInt(script, "GLUT_KEY_F5", GLUT_KEY_F5);
  bindInt(script, "GLUT_KEY_F6", GLUT_KEY_F6);
  bindInt(script, "GLUT_KEY_F7", GLUT_KEY_F7);
  bindInt(script, "GLUT_KEY_F8", GLUT_KEY_F8);
  bindInt(script, "GLUT_KEY_F9", GLUT_KEY_F9);
  bindInt(script, "GLUT_KEY_F10", GLUT_KEY_F10);
  bindInt(script, "GLUT_KEY_F11", GLUT_KEY_F11);
  bindInt(script, "GLUT_KEY_F12", GLUT_KEY_F12);
  bindInt(script, "GLUT_KEY_LEFT", GLUT_KEY_LEFT);
  bindInt(script, "GLUT_KEY_UP", GLUT_KEY_UP);
  bindInt(script, "GLUT_KEY_RIGHT", GLUT_KEY_RIGHT);
  bindInt(script, "GLUT_KEY_DOWN", GLUT_KEY_DOWN);
  bindInt(script, "GLUT_KEY_PAGE_UP", GLUT_KEY_PAGE_UP);
  bindInt(script, "GLUT_KEY_PAGE_DOWN", GLUT_KEY_PAGE_DOWN);
  bindInt(script, "GLUT_KEY_HOME", GLUT_KEY_HOME);
  bindInt(script, "GLUT_KEY_END", GLUT_KEY_END);
  bindInt(script, "GLUT_KEY_INSERT", GLUT_KEY_INSERT);
  bindInt(script, "GLUT_LEFT", GLUT_LEFT);
  bindInt(script, "GLUT_ENTERED", GLUT_ENTERED);
  bindInt(script, "GLUT_MENU_NOT_IN_USE", GLUT_MENU_NOT_IN_USE);
  bindInt(script, "GLUT_MENU_IN_USE", GLUT_MENU_IN_USE);
  bindInt(script, "GLUT_NOT_VISIBLE", GLUT_NOT_VISIBLE);
  bindInt(script, "GLUT_VISIBLE", GLUT_VISIBLE);
  bindInt(script, "GLUT_RED", GLUT_RED);
  bindInt(script, "GLUT_GREEN", GLUT_GREEN);
  bindInt(script, "GLUT_BLUE", GLUT_BLUE);
  bindInt(script, "GLUT_NORMAL", GLUT_NORMAL);
  bindInt(script, "GLUT_OVERLAY", GLUT_OVERLAY);
  bindAddr(script, "GLUT_STROKE_ROMAN", GLUT_STROKE_ROMAN);
  bindAddr(script, "GLUT_STROKE_MONO_ROMAN", GLUT_STROKE_MONO_ROMAN);
  bindAddr(script, "GLUT_BITMAP_9_BY_15", GLUT_BITMAP_9_BY_15);
  bindAddr(script, "GLUT_BITMAP_8_BY_13", GLUT_BITMAP_8_BY_13);
  bindAddr(script, "GLUT_BITMAP_TIMES_ROMAN_10", GLUT_BITMAP_TIMES_ROMAN_10);
  bindAddr(script, "GLUT_BITMAP_TIMES_ROMAN_24", GLUT_BITMAP_TIMES_ROMAN_24);
  bindAddr(script, "GLUT_BITMAP_HELVETICA_10", GLUT_BITMAP_HELVETICA_10);
  bindAddr(script, "GLUT_BITMAP_HELVETICA_12", GLUT_BITMAP_HELVETICA_12);
  bindAddr(script, "GLUT_BITMAP_HELVETICA_18", GLUT_BITMAP_HELVETICA_18);
  bindInt(script, "GLUT_WINDOW_X", GLUT_WINDOW_X);
  bindInt(script, "GLUT_WINDOW_Y", GLUT_WINDOW_Y);
  bindInt(script, "GLUT_WINDOW_WIDTH", GLUT_WINDOW_WIDTH);
  bindInt(script, "GLUT_WINDOW_HEIGHT", GLUT_WINDOW_HEIGHT);
  bindInt(script, "GLUT_WINDOW_BUFFER_SIZE", GLUT_WINDOW_BUFFER_SIZE);
  bindInt(script, "GLUT_WINDOW_STENCIL_SIZE", GLUT_WINDOW_STENCIL_SIZE);
  bindInt(script, "GLUT_WINDOW_DEPTH_SIZE", GLUT_WINDOW_DEPTH_SIZE);
  bindInt(script, "GLUT_WINDOW_RED_SIZE", GLUT_WINDOW_RED_SIZE);
  bindInt(script, "GLUT_WINDOW_GREEN_SIZE", GLUT_WINDOW_GREEN_SIZE);
  bindInt(script, "GLUT_WINDOW_BLUE_SIZE", GLUT_WINDOW_BLUE_SIZE);
  bindInt(script, "GLUT_WINDOW_ALPHA_SIZE", GLUT_WINDOW_ALPHA_SIZE);
  bindInt(script, "GLUT_WINDOW_ACCUM_RED_SIZE", GLUT_WINDOW_ACCUM_RED_SIZE);
  bindInt(script, "GLUT_WINDOW_ACCUM_GREEN_SIZE", GLUT_WINDOW_ACCUM_GREEN_SIZE);
  bindInt(script, "GLUT_WINDOW_ACCUM_BLUE_SIZE", GLUT_WINDOW_ACCUM_BLUE_SIZE);
  bindInt(script, "GLUT_WINDOW_ACCUM_ALPHA_SIZE", GLUT_WINDOW_ACCUM_ALPHA_SIZE);
  bindInt(script, "GLUT_WINDOW_DOUBLEBUFFER", GLUT_WINDOW_DOUBLEBUFFER);
  bindInt(script, "GLUT_WINDOW_RGBA", GLUT_WINDOW_RGBA);
  bindInt(script, "GLUT_WINDOW_PARENT", GLUT_WINDOW_PARENT);
  bindInt(script, "GLUT_WINDOW_NUM_CHILDREN", GLUT_WINDOW_NUM_CHILDREN);
  bindInt(script, "GLUT_WINDOW_COLORMAP_SIZE", GLUT_WINDOW_COLORMAP_SIZE);
  bindInt(script, "GLUT_WINDOW_NUM_SAMPLES", GLUT_WINDOW_NUM_SAMPLES);
  bindInt(script, "GLUT_WINDOW_STEREO", GLUT_WINDOW_STEREO);
  bindInt(script, "GLUT_WINDOW_CURSOR", GLUT_WINDOW_CURSOR);
  bindInt(script, "GLUT_SCREEN_WIDTH", GLUT_SCREEN_WIDTH);
  bindInt(script, "GLUT_SCREEN_HEIGHT", GLUT_SCREEN_HEIGHT);
  bindInt(script, "GLUT_SCREEN_WIDTH_MM", GLUT_SCREEN_WIDTH_MM);
  bindInt(script, "GLUT_SCREEN_HEIGHT_MM", GLUT_SCREEN_HEIGHT_MM);
  bindInt(script, "GLUT_MENU_NUM_ITEMS", GLUT_MENU_NUM_ITEMS);
  bindInt(script, "GLUT_DISPLAY_MODE_POSSIBLE", GLUT_DISPLAY_MODE_POSSIBLE);
  bindInt(script, "GLUT_INIT_WINDOW_X", GLUT_INIT_WINDOW_X);
  bindInt(script, "GLUT_INIT_WINDOW_Y", GLUT_INIT_WINDOW_Y);
  bindInt(script, "GLUT_INIT_WINDOW_WIDTH", GLUT_INIT_WINDOW_WIDTH);
  bindInt(script, "GLUT_INIT_WINDOW_HEIGHT", GLUT_INIT_WINDOW_HEIGHT);
  bindInt(script, "GLUT_INIT_DISPLAY_MODE", GLUT_INIT_DISPLAY_MODE);
  bindInt(script, "GLUT_ELAPSED_TIME", GLUT_ELAPSED_TIME);
  bindInt(script, "GLUT_HAS_KEYBOARD", GLUT_HAS_KEYBOARD);
  bindInt(script, "GLUT_HAS_MOUSE", GLUT_HAS_MOUSE);
  bindInt(script, "GLUT_HAS_SPACEBALL", GLUT_HAS_SPACEBALL);
  bindInt(script, "GLUT_HAS_DIAL_AND_BUTTON_BOX", GLUT_HAS_DIAL_AND_BUTTON_BOX);
  bindInt(script, "GLUT_HAS_TABLET", GLUT_HAS_TABLET);
  bindInt(script, "GLUT_NUM_MOUSE_BUTTONS", GLUT_NUM_MOUSE_BUTTONS);
  bindInt(script, "GLUT_NUM_SPACEBALL_BUTTONS", GLUT_NUM_SPACEBALL_BUTTONS);
  bindInt(script, "GLUT_NUM_BUTTON_BOX_BUTTONS", GLUT_NUM_BUTTON_BOX_BUTTONS);
  bindInt(script, "GLUT_NUM_DIALS", GLUT_NUM_DIALS);
  bindInt(script, "GLUT_NUM_TABLET_BUTTONS", GLUT_NUM_TABLET_BUTTONS);
  bindInt(script, "GLUT_OVERLAY_POSSIBLE", GLUT_OVERLAY_POSSIBLE);
  bindInt(script, "GLUT_LAYER_IN_USE", GLUT_LAYER_IN_USE);
  bindInt(script, "GLUT_HAS_OVERLAY", GLUT_HAS_OVERLAY);
  bindInt(script, "GLUT_TRANSPARENT_INDEX", GLUT_TRANSPARENT_INDEX);
  bindInt(script, "GLUT_NORMAL_DAMAGED", GLUT_NORMAL_DAMAGED);
  bindInt(script, "GLUT_OVERLAY_DAMAGED", GLUT_OVERLAY_DAMAGED);
  bindInt(script, "GLUT_NORMAL", GLUT_NORMAL);
  bindInt(script, "GLUT_OVERLAY", GLUT_OVERLAY);
  bindInt(script, "GLUT_ACTIVE_SHIFT", GLUT_ACTIVE_SHIFT);
  bindInt(script, "GLUT_ACTIVE_CTRL", GLUT_ACTIVE_CTRL);
  bindInt(script, "GLUT_ACTIVE_ALT", GLUT_ACTIVE_ALT);
  bindInt(script, "GLUT_CURSOR_RIGHT_ARROW", GLUT_CURSOR_RIGHT_ARROW);
  bindInt(script, "GLUT_CURSOR_LEFT_ARROW", GLUT_CURSOR_LEFT_ARROW);
  bindInt(script, "GLUT_CURSOR_INFO", GLUT_CURSOR_INFO);
  bindInt(script, "GLUT_CURSOR_DESTROY", GLUT_CURSOR_DESTROY);
  bindInt(script, "GLUT_CURSOR_HELP", GLUT_CURSOR_HELP);
  bindInt(script, "GLUT_CURSOR_CYCLE", GLUT_CURSOR_CYCLE);
  bindInt(script, "GLUT_CURSOR_SPRAY", GLUT_CURSOR_SPRAY);
  bindInt(script, "GLUT_CURSOR_WAIT", GLUT_CURSOR_WAIT);
  bindInt(script, "GLUT_CURSOR_TEXT", GLUT_CURSOR_TEXT);
  bindInt(script, "GLUT_CURSOR_CROSSHAIR", GLUT_CURSOR_CROSSHAIR);
  bindInt(script, "GLUT_CURSOR_UP_DOWN", GLUT_CURSOR_UP_DOWN);
  bindInt(script, "GLUT_CURSOR_LEFT_RIGHT", GLUT_CURSOR_LEFT_RIGHT);
  bindInt(script, "GLUT_CURSOR_TOP_SIDE", GLUT_CURSOR_TOP_SIDE);
  bindInt(script, "GLUT_CURSOR_BOTTOM_SIDE", GLUT_CURSOR_BOTTOM_SIDE);
  bindInt(script, "GLUT_CURSOR_LEFT_SIDE", GLUT_CURSOR_LEFT_SIDE);
  bindInt(script, "GLUT_CURSOR_RIGHT_SIDE", GLUT_CURSOR_RIGHT_SIDE);
  bindInt(script, "GLUT_CURSOR_TOP_LEFT_CORNER", GLUT_CURSOR_TOP_LEFT_CORNER);
  bindInt(script, "GLUT_CURSOR_TOP_RIGHT_CORNER", GLUT_CURSOR_TOP_RIGHT_CORNER);
  bindInt(script, "GLUT_CURSOR_BOTTOM_RIGHT_CORNER", GLUT_CURSOR_BOTTOM_RIGHT_CORNER);
  bindInt(script, "GLUT_CURSOR_BOTTOM_LEFT_CORNER", GLUT_CURSOR_BOTTOM_LEFT_CORNER);
  bindInt(script, "GLUT_CURSOR_INHERIT", GLUT_CURSOR_INHERIT);
  bindInt(script, "GLUT_CURSOR_NONE", GLUT_CURSOR_NONE);
  bindInt(script, "GLUT_CURSOR_FULL_CROSSHAIR", GLUT_CURSOR_FULL_CROSSHAIR);

}

/**************************************************************************/

/* ---------------------------------------------------------------------- */
Value *isis_glutInit(Script *script, char *proc_name, int call_data, 
                     int argc, Value **argv)
{
  /* extern void glutInit(int *argcp, char **argv); */

  checkCount(2, "argcp, argv");

  checkAddr(0, "argcp");
  checkAddr(1, "argv");

  glutInit ( (int *) getAddr(argv[0]),
             (char * *) getAddr(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutInitDisplayMode(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv)
{
  /* extern void glutInitDisplayMode(unsigned int mode); */

  checkCount(1, "mode");

  checkInt(0, "mode");

  glutInitDisplayMode ( (unsigned int) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutInitWindowPosition(Script *script, char *proc_name, int call_data, 
                                   int argc, Value **argv)
{
  /* extern void glutInitWindowPosition(int x, int y); */

  checkCount(2, "x, y");

  checkInt(0, "x");
  checkInt(1, "y");

  glutInitWindowPosition ( (int) getInt(argv[0]),
                           (int) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutInitWindowSize(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv)
{
  /* extern void glutInitWindowSize(int width, int height); */

  checkCount(2, "width, height");

  checkInt(0, "width");
  checkInt(1, "height");

  glutInitWindowSize ( (int) getInt(argv[0]),
                       (int) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutMainLoop(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv)
{
  /* extern void glutMainLoop(void); */

  checkCount(0, NULL);


  glutMainLoop (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutCreateWindow(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv)
{
  /* extern int glutCreateWindow(char *title); */

  int len;
  char *title;
  Value *retval;

  checkCount(1, "title");

  checkString(0, "title");

  len = Listsize(argv[0]) + 1;
  title = newStr(len);
  getString(argv[0], title, len);

  retval = newInt( glutCreateWindow ( (char *) title ) );

  freeStr(title);

  return retval;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutCreateSubWindow(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv)
{
  /* extern int glutCreateSubWindow(int win, int x, int y, int width, int height); */

  checkCount(5, "win, x, y, width, height");

  checkInt(0, "win");
  checkInt(1, "x");
  checkInt(2, "y");
  checkInt(3, "width");
  checkInt(4, "height");

  return newInt( glutCreateSubWindow ( (int) getInt(argv[0]),
                                       (int) getInt(argv[1]),
                                       (int) getInt(argv[2]),
                                       (int) getInt(argv[3]),
                                       (int) getInt(argv[4]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutDestroyWindow(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv)
{
  /* extern void glutDestroyWindow(int win); */

  checkCount(1, "win");

  checkInt(0, "win");

  glutDestroyWindow ( (int) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutPostRedisplay(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv)
{
  /* extern void glutPostRedisplay(void); */

  checkCount(0, NULL);


  glutPostRedisplay (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSwapBuffers(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern void glutSwapBuffers(void); */

  checkCount(0, NULL);


  glutSwapBuffers (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutGetWindow(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern int glutGetWindow(void); */

  checkCount(0, NULL);


  return newInt( glutGetWindow (  ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutSetWindow(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern void glutSetWindow(int win); */

  checkCount(1, "win");

  checkInt(0, "win");

  glutSetWindow ( (int) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSetWindowTitle(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv)
{
  /* extern void glutSetWindowTitle(char *title); */

  int len;
  char *title;

  checkCount(1, "title");

  checkString(0, "title");

  len = Listsize(argv[0]) + 1;
  title = newStr(len);
  getString(argv[0], title, len);

  glutSetWindowTitle ( (char *) title );

  freeStr(title);

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSetIconTitle(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv)
{
  /* extern void glutSetIconTitle(char *title); */

  int len;
  char *title;

  checkCount(1, "title");

  checkString(0, "title");

  len = Listsize(argv[0]) + 1;
  title = newStr(len);
  getString(argv[0], title, len);

  glutSetIconTitle ( (char *) title );

  freeStr(title);

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutPositionWindow(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv)
{
  /* extern void glutPositionWindow(int x, int y); */

  checkCount(2, "x, y");

  checkInt(0, "x");
  checkInt(1, "y");

  glutPositionWindow ( (int) getInt(argv[0]),
                       (int) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutReshapeWindow(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv)
{
  /* extern void glutReshapeWindow(int width, int height); */

  checkCount(2, "width, height");

  checkInt(0, "width");
  checkInt(1, "height");

  glutReshapeWindow ( (int) getInt(argv[0]),
                      (int) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutPopWindow(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern void glutPopWindow(void); */

  checkCount(0, NULL);


  glutPopWindow (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutPushWindow(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutPushWindow(void); */

  checkCount(0, NULL);


  glutPushWindow (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutIconifyWindow(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv)
{
  /* extern void glutIconifyWindow(void); */

  checkCount(0, NULL);


  glutIconifyWindow (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutShowWindow(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutShowWindow(void); */

  checkCount(0, NULL);


  glutShowWindow (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutHideWindow(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutHideWindow(void); */

  checkCount(0, NULL);


  glutHideWindow (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutFullScreen(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutFullScreen(void); */

  checkCount(0, NULL);


  glutFullScreen (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSetCursor(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern void glutSetCursor(int cursor); */

  checkCount(1, "cursor");

  checkInt(0, "cursor");

  glutSetCursor ( (int) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutEstablishOverlay(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv)
{
  /* extern void glutEstablishOverlay(void); */

  checkCount(0, NULL);


  glutEstablishOverlay (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutRemoveOverlay(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv)
{
  /* extern void glutRemoveOverlay(void); */

  checkCount(0, NULL);


  glutRemoveOverlay (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutUseLayer(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv)
{
  /* extern void glutUseLayer(GLenum layer); */

  checkCount(1, "layer");

  checkInt(0, "layer");

  glutUseLayer ( (GLenum) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutPostOverlayRedisplay(Script *script, char *proc_name, int call_data, 
                                     int argc, Value **argv)
{
  /* extern void glutPostOverlayRedisplay(void); */

  checkCount(0, NULL);


  glutPostOverlayRedisplay (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutShowOverlay(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern void glutShowOverlay(void); */

  checkCount(0, NULL);


  glutShowOverlay (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutHideOverlay(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern void glutHideOverlay(void); */

  checkCount(0, NULL);


  glutHideOverlay (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutCreateMenu(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern int glutCreateMenu(void (*)(int)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  return newInt( glutCreateMenu ( getAddr(argv[0]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutDestroyMenu(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern void glutDestroyMenu(int menu); */

  checkCount(1, "menu");

  checkInt(0, "menu");

  glutDestroyMenu ( (int) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutGetMenu(Script *script, char *proc_name, int call_data, 
                        int argc, Value **argv)
{
  /* extern int glutGetMenu(void); */

  checkCount(0, NULL);


  return newInt( glutGetMenu (  ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutSetMenu(Script *script, char *proc_name, int call_data, 
                        int argc, Value **argv)
{
  /* extern void glutSetMenu(int menu); */

  checkCount(1, "menu");

  checkInt(0, "menu");

  glutSetMenu ( (int) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutAddMenuEntry(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv)
{
  /* extern void glutAddMenuEntry(char *label, int value); */

  int len;
  char *label;

  checkCount(2, "label, value");

  checkString(0, "label");
  checkInt(1, "value");

  len = Listsize(argv[0]) + 1;
  label = newStr(len);
  getString(argv[0], label, len);

  glutAddMenuEntry ( (char *) label,
                     (int) getInt(argv[1]) );

  freeStr(label);

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutAddSubMenu(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutAddSubMenu(char *label, int submenu); */

  int len;
  char *label;

  checkCount(2, "label, submenu");

  checkString(0, "label");
  checkInt(1, "submenu");

  len = Listsize(argv[0]) + 1;
  label = newStr(len);
  getString(argv[0], label, len);

  glutAddSubMenu ( (char *) label,
                   (int) getInt(argv[1]) );

  freeStr(label);

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutChangeToMenuEntry(Script *script, char *proc_name, int call_data, 
                                  int argc, Value **argv)
{
  /* extern void glutChangeToMenuEntry(int item, char *label, int value); */

  int len;
  char *label;

  checkCount(3, "item, label, value");

  checkInt(0, "item");
  checkString(1, "label");
  checkInt(2, "value");

  len = Listsize(argv[1]) + 1;
  label = newStr(len);
  getString(argv[1], label, len);

  glutChangeToMenuEntry ( (int) getInt(argv[0]),
                          (char *) label,
                          (int) getInt(argv[2]) );

  freeStr(label);

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutChangeToSubMenu(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv)
{
  /* extern void glutChangeToSubMenu(int item, char *label, int submenu); */

  int len;
  char *label;

  checkCount(3, "item, label, submenu");

  checkInt(0, "item");
  checkString(1, "label");
  checkInt(2, "submenu");

  len = Listsize(argv[1]) + 1;
  label = newStr(len);
  getString(argv[1], label, len);

  glutChangeToSubMenu ( (int) getInt(argv[0]),
                        (char *) label,
                        (int) getInt(argv[2]) );

  freeStr(label);

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutRemoveMenuItem(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv)
{
  /* extern void glutRemoveMenuItem(int item); */

  checkCount(1, "item");

  checkInt(0, "item");

  glutRemoveMenuItem ( (int) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutAttachMenu(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutAttachMenu(int button); */

  checkCount(1, "button");

  checkInt(0, "button");

  glutAttachMenu ( (int) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutDetachMenu(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutDetachMenu(int button); */

  checkCount(1, "button");

  checkInt(0, "button");

  glutDetachMenu ( (int) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutDisplayFunc(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern void glutDisplayFunc(void (*)(void)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutDisplayFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutReshapeFunc(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern void glutReshapeFunc(void (*)(int width, int height)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutReshapeFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutKeyboardFunc(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv)
{
  /* extern void glutKeyboardFunc(void (*)(unsigned char key, int x, int y)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutKeyboardFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutMouseFunc(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern void glutMouseFunc(void (*)(int button, int state, int x, int y)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutMouseFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutMotionFunc(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutMotionFunc(void (*)(int x, int y)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutMotionFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutPassiveMotionFunc(Script *script, char *proc_name, int call_data, 
                                  int argc, Value **argv)
{
  /* extern void glutPassiveMotionFunc(void (*)(int x, int y)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutPassiveMotionFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutEntryFunc(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern void glutEntryFunc(void (*)(int state)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutEntryFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutVisibilityFunc(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv)
{
  /* extern void glutVisibilityFunc(void (*)(int state)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutVisibilityFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutIdleFunc(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv)
{
  /* extern void glutIdleFunc(void (*)(void)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutIdleFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutTimerFunc(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern void glutTimerFunc(unsigned int millis, void (*)(int value), int value); */

  checkCount(3, "millis, cfunc, value");

  checkInt(0, "millis");
  checkAddr(1, "cfunc");
  checkInt(2, "value");

  glutTimerFunc ( (unsigned int) getInt(argv[0]),
                  getAddr(argv[1]),
                  (int) getInt(argv[2]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutMenuStateFunc(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv)
{
  /* extern void glutMenuStateFunc(void (*)(int state)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutMenuStateFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSpecialFunc(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern void glutSpecialFunc(void (*)(int key, int x, int y)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutSpecialFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSpaceballMotionFunc(Script *script, char *proc_name, int call_data, 
                                    int argc, Value **argv)
{
  /* extern void glutSpaceballMotionFunc(void (*)(int x, int y, int z)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutSpaceballMotionFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSpaceballRotateFunc(Script *script, char *proc_name, int call_data, 
                                    int argc, Value **argv)
{
  /* extern void glutSpaceballRotateFunc(void (*)(int x, int y, int z)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutSpaceballRotateFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSpaceballButtonFunc(Script *script, char *proc_name, int call_data, 
                                    int argc, Value **argv)
{
  /* extern void glutSpaceballButtonFunc(void (*)(int button, int state)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutSpaceballButtonFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutButtonBoxFunc(Script *script, char *proc_name, int call_data, 
                              int argc, Value **argv)
{
  /* extern void glutButtonBoxFunc(void (*)(int button, int state)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutButtonBoxFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutDialsFunc(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern void glutDialsFunc(void (*)(int dial, int value)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutDialsFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutTabletMotionFunc(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv)
{
  /* extern void glutTabletMotionFunc(void (*)(int x, int y)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutTabletMotionFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutTabletButtonFunc(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv)
{
  /* extern void glutTabletButtonFunc(void (*)(int button, int state, int x, int y)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutTabletButtonFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutMenuStatusFunc(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv)
{
  /* extern void glutMenuStatusFunc(void (*)(int status, int x, int y)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutMenuStatusFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutOverlayDisplayFunc(Script *script, char *proc_name, int call_data, 
                                   int argc, Value **argv)
{
  /* extern void glutOverlayDisplayFunc(void (*)(void)); */

  checkCount(1, "cfunc");

  checkAddr(0, "cfunc");

  glutOverlayDisplayFunc ( getAddr(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSetColor(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv)
{
  /* extern void glutSetColor(int cell, GLfloat red, GLfloat green, GLfloat blue); */

  checkCount(4, "cell, red, green, blue");

  checkInt(0, "cell");
  checkReal(1, "red");
  checkReal(2, "green");
  checkReal(3, "blue");

  glutSetColor ( (int) getInt(argv[0]),
                 (GLfloat) getReal(argv[1]),
                 (GLfloat) getReal(argv[2]),
                 (GLfloat) getReal(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutGetColor(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv)
{
  /* extern GLfloat glutGetColor(int ndx, int component); */

  checkCount(2, "ndx, component");

  checkInt(0, "ndx");
  checkInt(1, "component");

  return newReal( glutGetColor ( (int) getInt(argv[0]),
                                 (int) getInt(argv[1]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutCopyColormap(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv)
{
  /* extern void glutCopyColormap(int win); */

  checkCount(1, "win");

  checkInt(0, "win");

  glutCopyColormap ( (int) getInt(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutGet(Script *script, char *proc_name, int call_data, 
                    int argc, Value **argv)
{
  /* extern int glutGet(GLenum type); */

  checkCount(1, "type");

  checkInt(0, "type");

  return newInt( glutGet ( (GLenum) getInt(argv[0]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutDeviceGet(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern int glutDeviceGet(GLenum type); */

  checkCount(1, "type");

  checkInt(0, "type");

  return newInt( glutDeviceGet ( (GLenum) getInt(argv[0]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutExtensionSupported(Script *script, char *proc_name, int call_data, 
                                   int argc, Value **argv)
{
  /* extern int glutExtensionSupported(char *name); */

  int len;
  char *name;
  Value *retval;

  checkCount(1, "name");

  checkString(0, "name");

  len = Listsize(argv[0]) + 1;
  name = newStr(len);
  getString(argv[0], name, len);

  retval = newInt( glutExtensionSupported ( (char *) name ) );

  freeStr(name);

  return retval;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutGetModifiers(Script *script, char *proc_name, int call_data, 
                             int argc, Value **argv)
{
  /* extern int glutGetModifiers(void); */

  checkCount(0, NULL);


  return newInt( glutGetModifiers (  ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutLayerGet(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv)
{
  /* extern int glutLayerGet(GLenum type); */

  checkCount(1, "type");

  checkInt(0, "type");

  return newInt( glutLayerGet ( (GLenum) getInt(argv[0]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutBitmapCharacter(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv)
{
  /* extern void glutBitmapCharacter(void *font, int character); */

  checkCount(2, "font, character");

  checkAddr(0, "font");
  checkInt(1, "character");

  glutBitmapCharacter ( (void *) getAddr(argv[0]),
                        (int) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutBitmapWidth(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern int glutBitmapWidth(void *font, int character); */

  checkCount(2, "font, character");

  checkAddr(0, "font");
  checkInt(1, "character");

  return newInt( glutBitmapWidth ( (void *) getAddr(argv[0]),
                                   (int) getInt(argv[1]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutStrokeCharacter(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv)
{
  /* extern void glutStrokeCharacter(void *font, int character); */

  checkCount(2, "font, character");

  checkAddr(0, "font");
  checkInt(1, "character");

  glutStrokeCharacter ( (void *) getAddr(argv[0]),
                        (int) getInt(argv[1]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutStrokeWidth(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern int glutStrokeWidth(void *font, int character); */

  checkCount(2, "font, character");

  checkAddr(0, "font");
  checkInt(1, "character");

  return newInt( glutStrokeWidth ( (void *) getAddr(argv[0]),
                                   (int) getInt(argv[1]) ) );

}

/* ---------------------------------------------------------------------- */
Value *isis_glutWireSphere(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutWireSphere(GLdouble radius, GLint slices, GLint stacks); */

  checkCount(3, "radius, slices, stacks");

  checkReal(0, "radius");
  checkInt(1, "slices");
  checkInt(2, "stacks");

  glutWireSphere ( (GLdouble) getReal(argv[0]),
                   (GLint) getInt(argv[1]),
                   (GLint) getInt(argv[2]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSolidSphere(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern void glutSolidSphere(GLdouble radius, GLint slices, GLint stacks); */

  checkCount(3, "radius, slices, stacks");

  checkReal(0, "radius");
  checkInt(1, "slices");
  checkInt(2, "stacks");

  glutSolidSphere ( (GLdouble) getReal(argv[0]),
                    (GLint) getInt(argv[1]),
                    (GLint) getInt(argv[2]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutWireCone(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv)
{
  /* extern void glutWireCone(GLdouble base, GLdouble height, GLint slices, GLint stacks); */

  checkCount(4, "base, height, slices, stacks");

  checkReal(0, "base");
  checkReal(1, "height");
  checkInt(2, "slices");
  checkInt(3, "stacks");

  glutWireCone ( (GLdouble) getReal(argv[0]),
                 (GLdouble) getReal(argv[1]),
                 (GLint) getInt(argv[2]),
                 (GLint) getInt(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSolidCone(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern void glutSolidCone(GLdouble base, GLdouble height, GLint slices, GLint stacks); */

  checkCount(4, "base, height, slices, stacks");

  checkReal(0, "base");
  checkReal(1, "height");
  checkInt(2, "slices");
  checkInt(3, "stacks");

  glutSolidCone ( (GLdouble) getReal(argv[0]),
                  (GLdouble) getReal(argv[1]),
                  (GLint) getInt(argv[2]),
                  (GLint) getInt(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutWireCube(Script *script, char *proc_name, int call_data, 
                         int argc, Value **argv)
{
  /* extern void glutWireCube(GLdouble size); */

  checkCount(1, "size");

  checkReal(0, "size");

  glutWireCube ( (GLdouble) getReal(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSolidCube(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern void glutSolidCube(GLdouble size); */

  checkCount(1, "size");

  checkReal(0, "size");

  glutSolidCube ( (GLdouble) getReal(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutWireTorus(Script *script, char *proc_name, int call_data, 
                          int argc, Value **argv)
{
  /* extern void glutWireTorus(GLdouble innerRadius, GLdouble outerRadius, GLint sides, GLint rings); */

  checkCount(4, "innerRadius, outerRadius, sides, rings");

  checkReal(0, "innerRadius");
  checkReal(1, "outerRadius");
  checkInt(2, "sides");
  checkInt(3, "rings");

  glutWireTorus ( (GLdouble) getReal(argv[0]),
                  (GLdouble) getReal(argv[1]),
                  (GLint) getInt(argv[2]),
                  (GLint) getInt(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSolidTorus(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutSolidTorus(GLdouble innerRadius, GLdouble outerRadius, GLint sides, GLint rings); */

  checkCount(4, "innerRadius, outerRadius, sides, rings");

  checkReal(0, "innerRadius");
  checkReal(1, "outerRadius");
  checkInt(2, "sides");
  checkInt(3, "rings");

  glutSolidTorus ( (GLdouble) getReal(argv[0]),
                   (GLdouble) getReal(argv[1]),
                   (GLint) getInt(argv[2]),
                   (GLint) getInt(argv[3]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutWireDodecahedron(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv)
{
  /* extern void glutWireDodecahedron(void); */

  checkCount(0, NULL);


  glutWireDodecahedron (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSolidDodecahedron(Script *script, char *proc_name, int call_data, 
                                  int argc, Value **argv)
{
  /* extern void glutSolidDodecahedron(void); */

  checkCount(0, NULL);


  glutSolidDodecahedron (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutWireTeapot(Script *script, char *proc_name, int call_data, 
                           int argc, Value **argv)
{
  /* extern void glutWireTeapot(GLdouble size); */

  checkCount(1, "size");

  checkReal(0, "size");

  glutWireTeapot ( (GLdouble) getReal(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSolidTeapot(Script *script, char *proc_name, int call_data, 
                            int argc, Value **argv)
{
  /* extern void glutSolidTeapot(GLdouble size); */

  checkCount(1, "size");

  checkReal(0, "size");

  glutSolidTeapot ( (GLdouble) getReal(argv[0]) );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutWireOctahedron(Script *script, char *proc_name, int call_data, 
                               int argc, Value **argv)
{
  /* extern void glutWireOctahedron(void); */

  checkCount(0, NULL);


  glutWireOctahedron (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSolidOctahedron(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv)
{
  /* extern void glutSolidOctahedron(void); */

  checkCount(0, NULL);


  glutSolidOctahedron (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutWireTetrahedron(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv)
{
  /* extern void glutWireTetrahedron(void); */

  checkCount(0, NULL);


  glutWireTetrahedron (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSolidTetrahedron(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv)
{
  /* extern void glutSolidTetrahedron(void); */

  checkCount(0, NULL);


  glutSolidTetrahedron (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutWireIcosahedron(Script *script, char *proc_name, int call_data, 
                                int argc, Value **argv)
{
  /* extern void glutWireIcosahedron(void); */

  checkCount(0, NULL);


  glutWireIcosahedron (  );

  return NullValue;
}

/* ---------------------------------------------------------------------- */
Value *isis_glutSolidIcosahedron(Script *script, char *proc_name, int call_data, 
                                 int argc, Value **argv)
{
  /* extern void glutSolidIcosahedron(void); */

  checkCount(0, NULL);


  glutSolidIcosahedron (  );

  return NullValue;
}


/**************************************************************************/

/* ---------------------------------------------------------------------- */
Value *isis_glut_update_callback_slot(Script *script, char *proc_name, int call_data,
                                      int argc, Value **argv)
{
  Procedure **procaddr;
  
  checkCount(2, "callback slot, callback procedure");
  checkAddr(0, "callback slot");
  if(!isNull(argv[1])) checkProc(1, "callback procedure");
  
  procaddr = (Procedure **) getAddr(argv[0]);
  if(*procaddr != NULL) freeProcedure(*procaddr);
  if(isNull(argv[1])) *procaddr = NULL;
  else *procaddr = referProcedure(getProc(argv[1]));
  
  return NullValue;
}

/* ---------------------------------------------------------------------- */
void glut_create_menu(int a)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(1);

  argv[0] = newInt(a);

  val = applyProcedure(localscript, glut_create_menu_proc, 1, argv);

  for(i = 0; i < 1; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_display(void)
{
  Value **argv, *val;

  argv = NULL;

  val = applyProcedure(localscript, glut_display_proc, 0, argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_reshape(int width, int height)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(2);

  argv[0] = newInt(width);
  argv[1] = newInt(height);

  val = applyProcedure(localscript, glut_reshape_proc, 2, argv);

  for(i = 0; i < 2; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_keyboard(unsigned char key, int x, int y)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(3);

  argv[0] = newInt(key);
  argv[1] = newInt(x);
  argv[2] = newInt(y);

  val = applyProcedure(localscript, glut_keyboard_proc, 3, argv);

  for(i = 0; i < 3; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_mouse(int button, int state, int x, int y)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(4);

  argv[0] = newInt(button);
  argv[1] = newInt(state);
  argv[2] = newInt(x);
  argv[3] = newInt(y);

  val = applyProcedure(localscript, glut_mouse_proc, 4, argv);

  for(i = 0; i < 4; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_motion(int x, int y)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(2);

  argv[0] = newInt(x);
  argv[1] = newInt(y);

  val = applyProcedure(localscript, glut_motion_proc, 2, argv);

  for(i = 0; i < 2; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_passive_motion(int x, int y)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(2);

  argv[0] = newInt(x);
  argv[1] = newInt(y);

  val = applyProcedure(localscript, glut_passive_motion_proc, 2, argv);

  for(i = 0; i < 2; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_entry(int state)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(1);

  argv[0] = newInt(state);

  val = applyProcedure(localscript, glut_entry_proc, 1, argv);

  for(i = 0; i < 1; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_visibility(int state)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(1);

  argv[0] = newInt(state);

  val = applyProcedure(localscript, glut_visibility_proc, 1, argv);

  for(i = 0; i < 1; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_idle(void)
{
  Value **argv, *val;

  argv = NULL;

  val = applyProcedure(localscript, glut_idle_proc, 0, argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_timer(int value)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(1);

  argv[0] = newInt(value);

  val = applyProcedure(localscript, glut_timer_proc, 1, argv);

  for(i = 0; i < 1; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_menu_state(int state)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(1);

  argv[0] = newInt(state);

  val = applyProcedure(localscript, glut_menu_state_proc, 1, argv);

  for(i = 0; i < 1; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_special(int key, int x, int y)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(3);

  argv[0] = newInt(key);
  argv[1] = newInt(x);
  argv[2] = newInt(y);

  val = applyProcedure(localscript, glut_special_proc, 3, argv);

  for(i = 0; i < 3; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_spaceball_motion(int x, int y, int z)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(3);

  argv[0] = newInt(x);
  argv[1] = newInt(y);
  argv[2] = newInt(z);

  val = applyProcedure(localscript, glut_spaceball_motion_proc, 3, argv);

  for(i = 0; i < 3; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_spaceball_rotate(int x, int y, int z)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(3);

  argv[0] = newInt(x);
  argv[1] = newInt(y);
  argv[2] = newInt(z);

  val = applyProcedure(localscript, glut_spaceball_rotate_proc, 3, argv);

  for(i = 0; i < 3; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_spaceball_button(int button, int state)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(2);

  argv[0] = newInt(button);
  argv[1] = newInt(state);

  val = applyProcedure(localscript, glut_spaceball_button_proc, 2, argv);

  for(i = 0; i < 2; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_button_box(int button, int state)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(2);

  argv[0] = newInt(button);
  argv[1] = newInt(state);

  val = applyProcedure(localscript, glut_button_box_proc, 2, argv);

  for(i = 0; i < 2; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_dials(int dial, int value)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(2);

  argv[0] = newInt(dial);
  argv[1] = newInt(value);

  val = applyProcedure(localscript, glut_dials_proc, 2, argv);

  for(i = 0; i < 2; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_tablet_motion(int x, int y)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(2);

  argv[0] = newInt(x);
  argv[1] = newInt(y);

  val = applyProcedure(localscript, glut_tablet_motion_proc, 2, argv);

  for(i = 0; i < 2; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_tablet_button(int button, int state, int x, int y)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(4);

  argv[0] = newInt(button);
  argv[1] = newInt(state);
  argv[2] = newInt(x);
  argv[3] = newInt(y);

  val = applyProcedure(localscript, glut_tablet_button_proc, 4, argv);

  for(i = 0; i < 4; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_menu_status(int status, int x, int y)
{
  int i;
  Value **argv, *val;

  argv = (Value **) newPtrArray(3);

  argv[0] = newInt(status);
  argv[1] = newInt(x);
  argv[2] = newInt(y);

  val = applyProcedure(localscript, glut_menu_status_proc, 3, argv);

  for(i = 0; i < 3; i++) freeValue(argv[i]);
  freePtrArray((void **) argv);

  freeValue(val);
}

/* ---------------------------------------------------------------------- */
void glut_overlay_display(void)
{
  Value **argv, *val;

  argv = NULL;

  val = applyProcedure(localscript, glut_overlay_display_proc, 0, argv);

  freeValue(val);
}

