/**************************************************************************/
/* Isis readline interface library 
   automatically generated by the Isis header file conversion utility
   written by Stefan Agamanolis */

#include <stdlib.h>
#include <stdio.h>
#include <isis.h>

#include <readline/readline.h>
#include <readline/history.h>

#include "isis_readline.h"

/**************************************************************************/

Value *isis_readline(Script *script, char *proc_name, int call_data, int argc, Value **argv);
Value *isis_add_history(Script *script, char *proc_name, int call_data, int argc, Value **argv);

/**************************************************************************/

void bind_readline_library(Script *script)
{
  bindBool(script, "isis_readline", 1);

  bindCfunc(script, "rl-readline", isis_readline, 0);
  bindCfunc(script, "rl-add-history", isis_add_history, 0);
}

/**************************************************************************/

/* ---------------------------------------------------------------------- */
Value *isis_readline(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* char *readline(char* prompt); */

  int len;
  char *prompt;
  char *retstr;
  Value *retval;

  checkCount(1, "prompt");

  checkString(0, "prompt");

  len = Listsize(argv[0]) + 1;
  prompt = newStr(len);
  if(prompt) getString(argv[0], prompt, len);

  retstr = (char *) readline ( (char *) prompt );

  if(retstr) retval = newString(strlen(retstr), retstr);
  else retval = NullValue;
  freeStr(prompt);

  /* added manually: */
  free(retstr);

  return retval;
}

/* ---------------------------------------------------------------------- */
Value *isis_add_history(Script *script, char *proc_name, int call_data, int argc, Value **argv)
{
  /* void add_history(char* hist_string); */

  int len;
  char *hist_string;

  checkCount(1, "hist_string");

  checkString(0, "hist_string");

  len = Listsize(argv[0]) + 1;
  hist_string = newStr(len);
  if(hist_string) getString(argv[0], hist_string, len);

  add_history ( (char *) hist_string );

  freeStr(hist_string);

  return NullValue;
}

